package service

import (
	fileService "github.com/sccicitb/pupr-backend/services/file"

	academicGuidanceService "github.com/sccicitb/pupr-backend/services/academic_guidance"
	accreditationService "github.com/sccicitb/pupr-backend/services/accreditation"
	adminService "github.com/sccicitb/pupr-backend/services/admin"
	adminActivityLogService "github.com/sccicitb/pupr-backend/services/admin_activity_log"
	announcementService "github.com/sccicitb/pupr-backend/services/announcement"
	authenticationService "github.com/sccicitb/pupr-backend/services/authentication"
	buildingService "github.com/sccicitb/pupr-backend/services/building"
	classService "github.com/sccicitb/pupr-backend/services/class"
	classAnnouncementService "github.com/sccicitb/pupr-backend/services/class_announcement"
	classDiscussionService "github.com/sccicitb/pupr-backend/services/class_discussion"
	classEventService "github.com/sccicitb/pupr-backend/services/class_event"
	classExamService "github.com/sccicitb/pupr-backend/services/class_exam"
	classGradeComponentService "github.com/sccicitb/pupr-backend/services/class_grade_component"
	classMaterialService "github.com/sccicitb/pupr-backend/services/class_material"
	classWorkService "github.com/sccicitb/pupr-backend/services/class_work"
	creditQuotaService "github.com/sccicitb/pupr-backend/services/credit_quota"
	curriculumService "github.com/sccicitb/pupr-backend/services/curriculum"
	diktiStudyProgramService "github.com/sccicitb/pupr-backend/services/dikti_study_program"
	documentActionService "github.com/sccicitb/pupr-backend/services/document_action"
	documentTypeService "github.com/sccicitb/pupr-backend/services/document_type"
	examSupervisorService "github.com/sccicitb/pupr-backend/services/exam_supervisor"
	examSupervisorRoleService "github.com/sccicitb/pupr-backend/services/exam_supervisor_role"
	excelService "github.com/sccicitb/pupr-backend/services/excel"
	expertiseGroupService "github.com/sccicitb/pupr-backend/services/expertise_group"
	facultyService "github.com/sccicitb/pupr-backend/services/faculty"
	gradeComponentService "github.com/sccicitb/pupr-backend/services/grade_component"
	gradeTypeService "github.com/sccicitb/pupr-backend/services/grade_type"
	graduationService "github.com/sccicitb/pupr-backend/services/graduation"
	graduationPredicateService "github.com/sccicitb/pupr-backend/services/graduation_predicate"
	graduationSessionService "github.com/sccicitb/pupr-backend/services/graduation_session"
	learningAchievementService "github.com/sccicitb/pupr-backend/services/learning_achievement"
	learningAchievementCategoryService "github.com/sccicitb/pupr-backend/services/learning_achievement_category"
	lectureService "github.com/sccicitb/pupr-backend/services/lecture"
	lecturerService "github.com/sccicitb/pupr-backend/services/lecturer"
	lecturerLeaveService "github.com/sccicitb/pupr-backend/services/lecturer_leave"
	lecturerMutationService "github.com/sccicitb/pupr-backend/services/lecturer_mutation"
	lecturerResignationService "github.com/sccicitb/pupr-backend/services/lecturer_resignation"
	lecturerStudentActivityLogService "github.com/sccicitb/pupr-backend/services/lecturer_student_activity_log"
	lessonPlanService "github.com/sccicitb/pupr-backend/services/lesson_plan"
	locationService "github.com/sccicitb/pupr-backend/services/location"
	majorService "github.com/sccicitb/pupr-backend/services/major"
	officerService "github.com/sccicitb/pupr-backend/services/officer"
	officerActionService "github.com/sccicitb/pupr-backend/services/officer_action"
	permissionService "github.com/sccicitb/pupr-backend/services/permission"
	reportService "github.com/sccicitb/pupr-backend/services/report"
	roleService "github.com/sccicitb/pupr-backend/services/role"
	roomService "github.com/sccicitb/pupr-backend/services/room"
	semesterService "github.com/sccicitb/pupr-backend/services/semester"
	sharedFileService "github.com/sccicitb/pupr-backend/services/shared_file"
	studentService "github.com/sccicitb/pupr-backend/services/student"
	studentActivityService "github.com/sccicitb/pupr-backend/services/student_activity"
	studentClassService "github.com/sccicitb/pupr-backend/services/student_class"
	studentLeaveService "github.com/sccicitb/pupr-backend/services/student_leave"
	studentSkpiService "github.com/sccicitb/pupr-backend/services/student_skpi"
	studentSubjectService "github.com/sccicitb/pupr-backend/services/student_subject"
	studyLevelService "github.com/sccicitb/pupr-backend/services/study_level"
	studyPlanService "github.com/sccicitb/pupr-backend/services/study_plan"
	studyProgramService "github.com/sccicitb/pupr-backend/services/study_program"
	subjectService "github.com/sccicitb/pupr-backend/services/subject"
	subjectCategoryService "github.com/sccicitb/pupr-backend/services/subject_category"
	subjectGradeComponentService "github.com/sccicitb/pupr-backend/services/subject_grade_component"
	thesisService "github.com/sccicitb/pupr-backend/services/thesis"
	thesisExaminerRoleService "github.com/sccicitb/pupr-backend/services/thesis_examiner_role"
	thesisSupervisorRoleService "github.com/sccicitb/pupr-backend/services/thesis_supervisor_role"
	yudiciumService "github.com/sccicitb/pupr-backend/services/yudicium"
	yudiciumSessionService "github.com/sccicitb/pupr-backend/services/yudicium_session"
	yudiciumTermService "github.com/sccicitb/pupr-backend/services/yudicium_term"
)

type ServiceCtx struct {
	FileService fileService.FileServiceInterface

	AcademicGuidanceService            academicGuidanceService.AcademicGuidanceServiceInterface
	AccreditationService               accreditationService.AccreditationServiceInterface
	AdminService                       adminService.AdminServiceInterface
	AnnouncementService                announcementService.AnnouncementServiceInterface
	AuthenticationService              authenticationService.AuthenticationServiceInterface
	AdminActivityLogService            adminActivityLogService.AdminActivityLogServiceInterface
	BuildingService                    buildingService.BuildingServiceInterface
	ClassService                       classService.ClassServiceInterface
	ClassAnnouncementService           classAnnouncementService.ClassAnnouncementServiceInterface
	ClassDiscussionService             classDiscussionService.ClassDiscussionServiceInterface
	ClassEventService                  classEventService.ClassEventServiceInterface
	ClassExamService                   classExamService.ClassExamServiceInterface
	ClassGradeComponentService         classGradeComponentService.ClassGradeComponentServiceInterface
	ClassMaterialService               classMaterialService.ClassMaterialServiceInterface
	ClassWorkService                   classWorkService.ClassWorkServiceInterface
	CreditQuotaService                 creditQuotaService.CreditQuotaServiceInterface
	CurriculumService                  curriculumService.CurriculumServiceInterface
	DiktiStudyProgramService           diktiStudyProgramService.DiktiStudyProgramServiceInterface
	DocumentActionService              documentActionService.DocumentActionServiceInterface
	DocumentTypeService                documentTypeService.DocumentTypeServiceInterface
	ExamSupervisorService              examSupervisorService.ExamSupervisorServiceInterface
	ExamSupervisorRoleService          examSupervisorRoleService.ExamSupervisorRoleServiceInterface
	ExpertiseGroupService              expertiseGroupService.ExpertiseGroupServiceInterface
	FacultyService                     facultyService.FacultyServiceInterface
	GradeComponentService              gradeComponentService.GradeComponentServiceInterface
	GradeTypeService                   gradeTypeService.GradeTypeServiceInterface
	GraduationService                  graduationService.GraduationServiceInterface
	GraduationPredicateService         graduationPredicateService.GraduationPredicateServiceInterface
	GraduationSessionService           graduationSessionService.GraduationSessionServiceInterface
	LearningAchievementService         learningAchievementService.LearningAchievementServiceInterface
	LearningAchievementCategoryService learningAchievementCategoryService.LearningAchievementCategoryServiceInterface
	LectureService                     lectureService.LectureServiceInterface
	LecturerService                    lecturerService.LecturerServiceInterface
	LecturerLeaveService               lecturerLeaveService.LecturerLeaveServiceInterface
	LecturerMutationService            lecturerMutationService.LecturerMutationServiceInterface
	LecturerResignationService         lecturerResignationService.LecturerResignationServiceInterface
	LecturerStudentActivityLogService  lecturerStudentActivityLogService.LecturerStudentActivityLogServiceInterface
	LessonPlanService                  lessonPlanService.LessonPlanServiceInterface
	LocationService                    locationService.LocationServiceInterface
	MajorService                       majorService.MajorServiceInterface
	OfficerService                     officerService.OfficerServiceInterface
	OfficerActionService               officerActionService.OfficerActionServiceInterface
	PermissionService                  permissionService.PermissionServiceInterface
	ReportService                      reportService.ReportServiceInterface
	RoleService                        roleService.RoleServiceInterface
	RoomService                        roomService.RoomServiceInterface
	SemesterService                    semesterService.SemesterServiceInterface
	SharedFileService                  sharedFileService.SharedFileServiceInterface
	StudentService                     studentService.StudentServiceInterface
	StudentActivityService             studentActivityService.StudentActivityServiceInterface
	StudentClassService                studentClassService.StudentClassServiceInterface
	StudentLeaveService                studentLeaveService.StudentLeaveServiceInterface
	StudentSkpiService                 studentSkpiService.StudentSkpiServiceInterface
	StudentSubjectService              studentSubjectService.StudentSubjectServiceInterface
	StudyLevelService                  studyLevelService.StudyLevelServiceInterface
	StudyPlanService                   studyPlanService.StudyPlanServiceInterface
	StudyProgramService                studyProgramService.StudyProgramServiceInterface
	SubjectService                     subjectService.SubjectServiceInterface
	SubjectCategoryService             subjectCategoryService.SubjectCategoryServiceInterface
	SubjectGradeComponentService       subjectGradeComponentService.SubjectGradeComponentServiceInterface
	ThesisService                      thesisService.ThesisServiceInterface
	ThesisExaminerRoleService          thesisExaminerRoleService.ThesisExaminerRoleServiceInterface
	ThesisSupervisorRoleService        thesisSupervisorRoleService.ThesisSupervisorRoleServiceInterface
	YudiciumService                    yudiciumService.YudiciumServiceInterface
	YudiciumSessionService             yudiciumSessionService.YudiciumSessionServiceInterface
	YudiciumTermService                yudiciumTermService.YudiciumTermServiceInterface
	ExcelService                       excelService.ExcelServiceInterface
}
