// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: student/transcript.proto

package transcript

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StudentTranscriptHandlerClient is the client API for StudentTranscriptHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StudentTranscriptHandlerClient interface {
	GetDetail(ctx context.Context, in *GetDetailRequest, opts ...grpc.CallOption) (*GetDetailResponse, error)
}

type studentTranscriptHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewStudentTranscriptHandlerClient(cc grpc.ClientConnInterface) StudentTranscriptHandlerClient {
	return &studentTranscriptHandlerClient{cc}
}

func (c *studentTranscriptHandlerClient) GetDetail(ctx context.Context, in *GetDetailRequest, opts ...grpc.CallOption) (*GetDetailResponse, error) {
	out := new(GetDetailResponse)
	err := c.cc.Invoke(ctx, "/student_transcript.StudentTranscriptHandler/GetDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudentTranscriptHandlerServer is the server API for StudentTranscriptHandler service.
// All implementations must embed UnimplementedStudentTranscriptHandlerServer
// for forward compatibility
type StudentTranscriptHandlerServer interface {
	GetDetail(context.Context, *GetDetailRequest) (*GetDetailResponse, error)
	mustEmbedUnimplementedStudentTranscriptHandlerServer()
}

// UnimplementedStudentTranscriptHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedStudentTranscriptHandlerServer struct {
}

func (UnimplementedStudentTranscriptHandlerServer) GetDetail(context.Context, *GetDetailRequest) (*GetDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDetail not implemented")
}
func (UnimplementedStudentTranscriptHandlerServer) mustEmbedUnimplementedStudentTranscriptHandlerServer() {
}

// UnsafeStudentTranscriptHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StudentTranscriptHandlerServer will
// result in compilation errors.
type UnsafeStudentTranscriptHandlerServer interface {
	mustEmbedUnimplementedStudentTranscriptHandlerServer()
}

func RegisterStudentTranscriptHandlerServer(s grpc.ServiceRegistrar, srv StudentTranscriptHandlerServer) {
	s.RegisterService(&StudentTranscriptHandler_ServiceDesc, srv)
}

func _StudentTranscriptHandler_GetDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentTranscriptHandlerServer).GetDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/student_transcript.StudentTranscriptHandler/GetDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentTranscriptHandlerServer).GetDetail(ctx, req.(*GetDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StudentTranscriptHandler_ServiceDesc is the grpc.ServiceDesc for StudentTranscriptHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StudentTranscriptHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "student_transcript.StudentTranscriptHandler",
	HandlerType: (*StudentTranscriptHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDetail",
			Handler:    _StudentTranscriptHandler_GetDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "student/transcript.proto",
}
