package repository

import (
	academicGuidanceRepo "github.com/sccicitb/pupr-backend/data/repositories/academic_guidance"
	accreditationRepo "github.com/sccicitb/pupr-backend/data/repositories/accreditation"
	adminRepo "github.com/sccicitb/pupr-backend/data/repositories/admin"
	adminActivityLogRepo "github.com/sccicitb/pupr-backend/data/repositories/admin_activity_log"
	announcementRepo "github.com/sccicitb/pupr-backend/data/repositories/announcement"
	authenticationRepo "github.com/sccicitb/pupr-backend/data/repositories/authentication"
	buildingRepo "github.com/sccicitb/pupr-backend/data/repositories/building"
	classRepo "github.com/sccicitb/pupr-backend/data/repositories/class"
	classAnnouncementRepo "github.com/sccicitb/pupr-backend/data/repositories/class_announcement"
	classDiscussionRepo "github.com/sccicitb/pupr-backend/data/repositories/class_discussion"
	classEventRepo "github.com/sccicitb/pupr-backend/data/repositories/class_event"
	classExamRepo "github.com/sccicitb/pupr-backend/data/repositories/class_exam"
	classGradeComponentRepo "github.com/sccicitb/pupr-backend/data/repositories/class_grade_component"
	classLecturerRepo "github.com/sccicitb/pupr-backend/data/repositories/class_lecturer"
	classMaterialRepo "github.com/sccicitb/pupr-backend/data/repositories/class_material"
	classWorkRepo "github.com/sccicitb/pupr-backend/data/repositories/class_work"
	creditQuotaRepo "github.com/sccicitb/pupr-backend/data/repositories/credit_quota"
	curriculumRepo "github.com/sccicitb/pupr-backend/data/repositories/curriculum"
	diktiStudyProgramRepo "github.com/sccicitb/pupr-backend/data/repositories/dikti_study_program"
	documentActionRepo "github.com/sccicitb/pupr-backend/data/repositories/document_action"
	documentTypeRepo "github.com/sccicitb/pupr-backend/data/repositories/document_type"
	examSupervisorRepo "github.com/sccicitb/pupr-backend/data/repositories/exam_supervisor"
	examSupervisorRoleRepo "github.com/sccicitb/pupr-backend/data/repositories/exam_supervisor_role"
	excelRepo "github.com/sccicitb/pupr-backend/data/repositories/excel"
	expertiseGroupRepo "github.com/sccicitb/pupr-backend/data/repositories/expertise_group"
	facultyRepo "github.com/sccicitb/pupr-backend/data/repositories/faculty"
	gradeComponentRepo "github.com/sccicitb/pupr-backend/data/repositories/grade_component"
	gradeTypeRepo "github.com/sccicitb/pupr-backend/data/repositories/grade_type"
	graduationPredicateRepo "github.com/sccicitb/pupr-backend/data/repositories/graduation_predicate"
	graduationSessionRepo "github.com/sccicitb/pupr-backend/data/repositories/graduation_session"
	graduationStudentRepo "github.com/sccicitb/pupr-backend/data/repositories/graduation_student"
	learningAchievementRepo "github.com/sccicitb/pupr-backend/data/repositories/learning_achievement"
	learningAchievementCategoryRepo "github.com/sccicitb/pupr-backend/data/repositories/learning_achievement_category"
	lectureRepo "github.com/sccicitb/pupr-backend/data/repositories/lecture"
	lecturerRepo "github.com/sccicitb/pupr-backend/data/repositories/lecturer"
	lecturerLeaveRepo "github.com/sccicitb/pupr-backend/data/repositories/lecturer_leave"
	lecturerMutationRepo "github.com/sccicitb/pupr-backend/data/repositories/lecturer_mutation"
	lecturerResignationRepo "github.com/sccicitb/pupr-backend/data/repositories/lecturer_resignation"
	lecturerStudentActivityLogRepo "github.com/sccicitb/pupr-backend/data/repositories/lecturer_student_activity_log"
	lessonPlanRepo "github.com/sccicitb/pupr-backend/data/repositories/lesson_plan"
	locationRepo "github.com/sccicitb/pupr-backend/data/repositories/location"
	majorRepo "github.com/sccicitb/pupr-backend/data/repositories/major"
	officerRepo "github.com/sccicitb/pupr-backend/data/repositories/officer"
	officerActionRepo "github.com/sccicitb/pupr-backend/data/repositories/officer_action"
	permissionRepo "github.com/sccicitb/pupr-backend/data/repositories/permission"
	reportRepo "github.com/sccicitb/pupr-backend/data/repositories/report"
	roleRepo "github.com/sccicitb/pupr-backend/data/repositories/role"
	roomRepo "github.com/sccicitb/pupr-backend/data/repositories/room"
	semesterRepo "github.com/sccicitb/pupr-backend/data/repositories/semester"
	sharedFileRepo "github.com/sccicitb/pupr-backend/data/repositories/shared_file"
	studentRepo "github.com/sccicitb/pupr-backend/data/repositories/student"
	studentActivityRepo "github.com/sccicitb/pupr-backend/data/repositories/student_activity"
	studentClassRepo "github.com/sccicitb/pupr-backend/data/repositories/student_class"
	studentLeaveRepo "github.com/sccicitb/pupr-backend/data/repositories/student_leave"
	studentSkpiRepo "github.com/sccicitb/pupr-backend/data/repositories/student_skpi"
	studyLevelRepo "github.com/sccicitb/pupr-backend/data/repositories/study_level"
	studyPlanRepo "github.com/sccicitb/pupr-backend/data/repositories/study_plan"
	studyProgramRepo "github.com/sccicitb/pupr-backend/data/repositories/study_program"
	subjectRepo "github.com/sccicitb/pupr-backend/data/repositories/subject"
	subjectCategoryRepo "github.com/sccicitb/pupr-backend/data/repositories/subject_category"
	subjectEquivalenceRepo "github.com/sccicitb/pupr-backend/data/repositories/subject_equivalence"
	subjectGradeComponentRepo "github.com/sccicitb/pupr-backend/data/repositories/subject_grade_component"
	subjectPrerequisiteRepo "github.com/sccicitb/pupr-backend/data/repositories/subject_prerequisite"
	thesisRepo "github.com/sccicitb/pupr-backend/data/repositories/thesis"
	thesisExaminerRoleRepo "github.com/sccicitb/pupr-backend/data/repositories/thesis_examiner_role"
	thesisSupervisorRoleRepo "github.com/sccicitb/pupr-backend/data/repositories/thesis_supervisor_role"
	yudiciumSessionRepo "github.com/sccicitb/pupr-backend/data/repositories/yudicium_session"
	yudiciumStudentRepo "github.com/sccicitb/pupr-backend/data/repositories/yudicium_student"
	yudiciumTermRepo "github.com/sccicitb/pupr-backend/data/repositories/yudicium_term"
)

type RepoCtx struct {
	AdminActivityLogRepo            adminActivityLogRepo.AdminActivityLogInterface
	AcademicGuidanceRepo            academicGuidanceRepo.AcademicGuidanceRepositoryInterface
	AccreditationRepo               accreditationRepo.AccreditationRepositoryInterface
	AdminRepo                       adminRepo.AdminRepositoryInterface
	AnnouncementRepo                announcementRepo.AnnouncementRepositoryInterface
	AuthenticationRepo              authenticationRepo.AuthenticationRepositoryInterface
	BuildingRepo                    buildingRepo.BuildingRepositoryInterface
	ClassRepo                       classRepo.ClassRepositoryInterface
	ClassAnnouncementRepo           classAnnouncementRepo.ClassAnnouncementRepositoryInterface
	ClassDiscussionRepo             classDiscussionRepo.ClassDiscussionRepositoryInterface
	ClassEventRepo                  classEventRepo.ClassEventRepositoryInterface
	ClassExamRepo                   classExamRepo.ClassExamRepositoryInterface
	ClassGradeComponentRepo         classGradeComponentRepo.ClassGradeComponentRepositoryInterface
	ClassLecturerRepo               classLecturerRepo.ClassLecturerRepositoryInterface
	ClassMaterialRepo               classMaterialRepo.ClassMaterialRepositoryInterface
	ClassWorkRepo                   classWorkRepo.ClassWorkRepositoryInterface
	CreditQuotaRepo                 creditQuotaRepo.CreditQuotaRepositoryInterface
	CurriculumRepo                  curriculumRepo.CurriculumRepositoryInterface
	DiktiStudyProgramRepo           diktiStudyProgramRepo.DiktiStudyProgramRepositoryInterface
	DocumentActionRepo              documentActionRepo.DocumentActionRepositoryInterface
	DocumentTypeRepo                documentTypeRepo.DocumentTypeRepositoryInterface
	ExamSupervisorRepo              examSupervisorRepo.ExamSupervisorRepositoryInterface
	ExamSupervisorRoleRepo          examSupervisorRoleRepo.ExamSupervisorRoleRepositoryInterface
	ExpertiseGroupRepo              expertiseGroupRepo.ExpertiseGroupRepositoryInterface
	FacultyRepo                     facultyRepo.FacultyRepositoryInterface
	GradeComponentRepo              gradeComponentRepo.GradeComponentRepositoryInterface
	GradeTypeRepo                   gradeTypeRepo.GradeTypeRepositoryInterface
	GraduationPredicateRepo         graduationPredicateRepo.GraduationPredicateRepositoryInterface
	GraduationSessionRepo           graduationSessionRepo.GraduationSessionRepositoryInterface
	GraduationStudentRepo           graduationStudentRepo.GraduationStudentRepositoryInterface
	LectureRepo                     lectureRepo.LectureRepositoryInterface
	LecturerRepo                    lecturerRepo.LecturerRepositoryInterface
	LecturerLeaveRepo               lecturerLeaveRepo.LecturerLeaveRepositoryInterface
	LecturerMutationRepo            lecturerMutationRepo.LecturerMutationRepositoryInterface
	LecturerResignationRepo         lecturerResignationRepo.LecturerResignationRepositoryInterface
	LecturerStudentActivityLogRepo  lecturerStudentActivityLogRepo.LecturerStudentActivityLogInterface
	LearningAchievementRepo         learningAchievementRepo.LearningAchievementRepositoryInterface
	LearningAchievementCategoryRepo learningAchievementCategoryRepo.LearningAchievementCategoryRepositoryInterface
	LessonPlanRepo                  lessonPlanRepo.LessonPlanRepositoryInterface
	LocationRepo                    locationRepo.LocationRepositoryInterface
	MajorRepo                       majorRepo.MajorRepositoryInterface
	OfficerRepo                     officerRepo.OfficerRepositoryInterface
	OfficerActionRepo               officerActionRepo.OfficerActionRepositoryInterface
	PermissionRepo                  permissionRepo.PermissionRepositoryInterface
	ReportRepo                      reportRepo.ReportRepositoryInterface
	RoleRepo                        roleRepo.RoleRepositoryInterface
	RoomRepo                        roomRepo.RoomRepositoryInterface
	SemesterRepo                    semesterRepo.SemesterRepositoryInterface
	SharedFileRepo                  sharedFileRepo.SharedFileRepositoryInterface
	StudentRepo                     studentRepo.StudentRepositoryInterface
	StudentActivityRepo             studentActivityRepo.StudentActivityRepositoryInterface
	StudentClassRepo                studentClassRepo.StudentClassRepositoryInterface
	StudentLeaveRepo                studentLeaveRepo.StudentLeaveRepositoryInterface
	StudentSkpiRepo                 studentSkpiRepo.StudentSkpiRepositoryInterface
	StudyLevelRepo                  studyLevelRepo.StudyLevelRepositoryInterface
	StudyPlanRepo                   studyPlanRepo.StudyPlanRepositoryInterface
	StudyProgramRepo                studyProgramRepo.StudyProgramRepositoryInterface
	SubjectRepo                     subjectRepo.SubjectRepositoryInterface
	SubjectCategoryRepo             subjectCategoryRepo.SubjectCategoryRepositoryInterface
	SubjectEquivalenceRepo          subjectEquivalenceRepo.SubjectEquivalenceRepositoryInterface
	SubjectGradeComponentRepo       subjectGradeComponentRepo.SubjectGradeComponentRepositoryInterface
	SubjectPrerequisiteRepo         subjectPrerequisiteRepo.SubjectPrerequisiteRepositoryInterface
	ThesisRepo                      thesisRepo.ThesisRepositoryInterface
	ThesisExaminerRoleRepo          thesisExaminerRoleRepo.ThesisExaminerRoleRepositoryInterface
	ThesisSupervisorRoleRepo        thesisSupervisorRoleRepo.ThesisSupervisorRoleRepositoryInterface
	YudiciumSessionRepo             yudiciumSessionRepo.YudiciumSessionRepositoryInterface
	YudiciumStudentRepo             yudiciumStudentRepo.YudiciumStudentRepositoryInterface
	YudiciumTermRepo                yudiciumTermRepo.YudiciumTermRepositoryInterface
	ExcelRepo                       excelRepo.ExcelRepositoryInterface
}
