// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: admin/grade_component.proto

package grade_component

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdminGradeComponentHandlerClient is the client API for AdminGradeComponentHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminGradeComponentHandlerClient interface {
	GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	GetListBySubjectCategory(ctx context.Context, in *GetListBySubjectCategoryRequest, opts ...grpc.CallOption) (*GetListBySubjectCategoryResponse, error)
	BulkUpdatePercentage(ctx context.Context, in *BulkUpdatePercentageRequest, opts ...grpc.CallOption) (*BulkUpdatePercentageResponse, error)
}

type adminGradeComponentHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminGradeComponentHandlerClient(cc grpc.ClientConnInterface) AdminGradeComponentHandlerClient {
	return &adminGradeComponentHandlerClient{cc}
}

func (c *adminGradeComponentHandlerClient) GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponse, error) {
	out := new(GetListResponse)
	err := c.cc.Invoke(ctx, "/admin_grade_component.AdminGradeComponentHandler/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminGradeComponentHandlerClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/admin_grade_component.AdminGradeComponentHandler/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminGradeComponentHandlerClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/admin_grade_component.AdminGradeComponentHandler/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminGradeComponentHandlerClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/admin_grade_component.AdminGradeComponentHandler/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminGradeComponentHandlerClient) GetListBySubjectCategory(ctx context.Context, in *GetListBySubjectCategoryRequest, opts ...grpc.CallOption) (*GetListBySubjectCategoryResponse, error) {
	out := new(GetListBySubjectCategoryResponse)
	err := c.cc.Invoke(ctx, "/admin_grade_component.AdminGradeComponentHandler/GetListBySubjectCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminGradeComponentHandlerClient) BulkUpdatePercentage(ctx context.Context, in *BulkUpdatePercentageRequest, opts ...grpc.CallOption) (*BulkUpdatePercentageResponse, error) {
	out := new(BulkUpdatePercentageResponse)
	err := c.cc.Invoke(ctx, "/admin_grade_component.AdminGradeComponentHandler/BulkUpdatePercentage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminGradeComponentHandlerServer is the server API for AdminGradeComponentHandler service.
// All implementations must embed UnimplementedAdminGradeComponentHandlerServer
// for forward compatibility
type AdminGradeComponentHandlerServer interface {
	GetList(context.Context, *GetListRequest) (*GetListResponse, error)
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	GetListBySubjectCategory(context.Context, *GetListBySubjectCategoryRequest) (*GetListBySubjectCategoryResponse, error)
	BulkUpdatePercentage(context.Context, *BulkUpdatePercentageRequest) (*BulkUpdatePercentageResponse, error)
	mustEmbedUnimplementedAdminGradeComponentHandlerServer()
}

// UnimplementedAdminGradeComponentHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedAdminGradeComponentHandlerServer struct {
}

func (UnimplementedAdminGradeComponentHandlerServer) GetList(context.Context, *GetListRequest) (*GetListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedAdminGradeComponentHandlerServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedAdminGradeComponentHandlerServer) Update(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedAdminGradeComponentHandlerServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAdminGradeComponentHandlerServer) GetListBySubjectCategory(context.Context, *GetListBySubjectCategoryRequest) (*GetListBySubjectCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListBySubjectCategory not implemented")
}
func (UnimplementedAdminGradeComponentHandlerServer) BulkUpdatePercentage(context.Context, *BulkUpdatePercentageRequest) (*BulkUpdatePercentageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkUpdatePercentage not implemented")
}
func (UnimplementedAdminGradeComponentHandlerServer) mustEmbedUnimplementedAdminGradeComponentHandlerServer() {
}

// UnsafeAdminGradeComponentHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminGradeComponentHandlerServer will
// result in compilation errors.
type UnsafeAdminGradeComponentHandlerServer interface {
	mustEmbedUnimplementedAdminGradeComponentHandlerServer()
}

func RegisterAdminGradeComponentHandlerServer(s grpc.ServiceRegistrar, srv AdminGradeComponentHandlerServer) {
	s.RegisterService(&AdminGradeComponentHandler_ServiceDesc, srv)
}

func _AdminGradeComponentHandler_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminGradeComponentHandlerServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_grade_component.AdminGradeComponentHandler/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminGradeComponentHandlerServer).GetList(ctx, req.(*GetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminGradeComponentHandler_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminGradeComponentHandlerServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_grade_component.AdminGradeComponentHandler/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminGradeComponentHandlerServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminGradeComponentHandler_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminGradeComponentHandlerServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_grade_component.AdminGradeComponentHandler/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminGradeComponentHandlerServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminGradeComponentHandler_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminGradeComponentHandlerServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_grade_component.AdminGradeComponentHandler/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminGradeComponentHandlerServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminGradeComponentHandler_GetListBySubjectCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListBySubjectCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminGradeComponentHandlerServer).GetListBySubjectCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_grade_component.AdminGradeComponentHandler/GetListBySubjectCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminGradeComponentHandlerServer).GetListBySubjectCategory(ctx, req.(*GetListBySubjectCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminGradeComponentHandler_BulkUpdatePercentage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkUpdatePercentageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminGradeComponentHandlerServer).BulkUpdatePercentage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_grade_component.AdminGradeComponentHandler/BulkUpdatePercentage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminGradeComponentHandlerServer).BulkUpdatePercentage(ctx, req.(*BulkUpdatePercentageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminGradeComponentHandler_ServiceDesc is the grpc.ServiceDesc for AdminGradeComponentHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminGradeComponentHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin_grade_component.AdminGradeComponentHandler",
	HandlerType: (*AdminGradeComponentHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _AdminGradeComponentHandler_GetList_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _AdminGradeComponentHandler_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AdminGradeComponentHandler_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AdminGradeComponentHandler_Delete_Handler,
		},
		{
			MethodName: "GetListBySubjectCategory",
			Handler:    _AdminGradeComponentHandler_GetListBySubjectCategory_Handler,
		},
		{
			MethodName: "BulkUpdatePercentage",
			Handler:    _AdminGradeComponentHandler_BulkUpdatePercentage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/grade_component.proto",
}
