// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: admin/lecturer_resignation.proto

package lecturer_resignation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdminLecturerResignationHandlerClient is the client API for AdminLecturerResignationHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminLecturerResignationHandlerClient interface {
	GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type adminLecturerResignationHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminLecturerResignationHandlerClient(cc grpc.ClientConnInterface) AdminLecturerResignationHandlerClient {
	return &adminLecturerResignationHandlerClient{cc}
}

func (c *adminLecturerResignationHandlerClient) GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponse, error) {
	out := new(GetListResponse)
	err := c.cc.Invoke(ctx, "/admin_lecturer_resignation.AdminLecturerResignationHandler/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminLecturerResignationHandlerClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/admin_lecturer_resignation.AdminLecturerResignationHandler/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminLecturerResignationHandlerServer is the server API for AdminLecturerResignationHandler service.
// All implementations must embed UnimplementedAdminLecturerResignationHandlerServer
// for forward compatibility
type AdminLecturerResignationHandlerServer interface {
	GetList(context.Context, *GetListRequest) (*GetListResponse, error)
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	mustEmbedUnimplementedAdminLecturerResignationHandlerServer()
}

// UnimplementedAdminLecturerResignationHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedAdminLecturerResignationHandlerServer struct {
}

func (UnimplementedAdminLecturerResignationHandlerServer) GetList(context.Context, *GetListRequest) (*GetListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedAdminLecturerResignationHandlerServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedAdminLecturerResignationHandlerServer) mustEmbedUnimplementedAdminLecturerResignationHandlerServer() {
}

// UnsafeAdminLecturerResignationHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminLecturerResignationHandlerServer will
// result in compilation errors.
type UnsafeAdminLecturerResignationHandlerServer interface {
	mustEmbedUnimplementedAdminLecturerResignationHandlerServer()
}

func RegisterAdminLecturerResignationHandlerServer(s grpc.ServiceRegistrar, srv AdminLecturerResignationHandlerServer) {
	s.RegisterService(&AdminLecturerResignationHandler_ServiceDesc, srv)
}

func _AdminLecturerResignationHandler_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminLecturerResignationHandlerServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_lecturer_resignation.AdminLecturerResignationHandler/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminLecturerResignationHandlerServer).GetList(ctx, req.(*GetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminLecturerResignationHandler_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminLecturerResignationHandlerServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_lecturer_resignation.AdminLecturerResignationHandler/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminLecturerResignationHandlerServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminLecturerResignationHandler_ServiceDesc is the grpc.ServiceDesc for AdminLecturerResignationHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminLecturerResignationHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin_lecturer_resignation.AdminLecturerResignationHandler",
	HandlerType: (*AdminLecturerResignationHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _AdminLecturerResignationHandler_GetList_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _AdminLecturerResignationHandler_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/lecturer_resignation.proto",
}
