// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: lecturer/semester.proto

package semester

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LecturerSemesterHandlerClient is the client API for LecturerSemesterHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LecturerSemesterHandlerClient interface {
	GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponse, error)
}

type lecturerSemesterHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewLecturerSemesterHandlerClient(cc grpc.ClientConnInterface) LecturerSemesterHandlerClient {
	return &lecturerSemesterHandlerClient{cc}
}

func (c *lecturerSemesterHandlerClient) GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponse, error) {
	out := new(GetListResponse)
	err := c.cc.Invoke(ctx, "/lecturer_semester.LecturerSemesterHandler/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LecturerSemesterHandlerServer is the server API for LecturerSemesterHandler service.
// All implementations must embed UnimplementedLecturerSemesterHandlerServer
// for forward compatibility
type LecturerSemesterHandlerServer interface {
	GetList(context.Context, *GetListRequest) (*GetListResponse, error)
	mustEmbedUnimplementedLecturerSemesterHandlerServer()
}

// UnimplementedLecturerSemesterHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedLecturerSemesterHandlerServer struct {
}

func (UnimplementedLecturerSemesterHandlerServer) GetList(context.Context, *GetListRequest) (*GetListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedLecturerSemesterHandlerServer) mustEmbedUnimplementedLecturerSemesterHandlerServer() {
}

// UnsafeLecturerSemesterHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LecturerSemesterHandlerServer will
// result in compilation errors.
type UnsafeLecturerSemesterHandlerServer interface {
	mustEmbedUnimplementedLecturerSemesterHandlerServer()
}

func RegisterLecturerSemesterHandlerServer(s grpc.ServiceRegistrar, srv LecturerSemesterHandlerServer) {
	s.RegisterService(&LecturerSemesterHandler_ServiceDesc, srv)
}

func _LecturerSemesterHandler_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LecturerSemesterHandlerServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lecturer_semester.LecturerSemesterHandler/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LecturerSemesterHandlerServer).GetList(ctx, req.(*GetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LecturerSemesterHandler_ServiceDesc is the grpc.ServiceDesc for LecturerSemesterHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LecturerSemesterHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lecturer_semester.LecturerSemesterHandler",
	HandlerType: (*LecturerSemesterHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _LecturerSemesterHandler_GetList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lecturer/semester.proto",
}
