// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: root/lecturer.proto

package lecturer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RootLecturerHandlerClient is the client API for RootLecturerHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RootLecturerHandlerClient interface {
	GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponse, error)
}

type rootLecturerHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewRootLecturerHandlerClient(cc grpc.ClientConnInterface) RootLecturerHandlerClient {
	return &rootLecturerHandlerClient{cc}
}

func (c *rootLecturerHandlerClient) GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponse, error) {
	out := new(GetListResponse)
	err := c.cc.Invoke(ctx, "/root_lecturer.RootLecturerHandler/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RootLecturerHandlerServer is the server API for RootLecturerHandler service.
// All implementations must embed UnimplementedRootLecturerHandlerServer
// for forward compatibility
type RootLecturerHandlerServer interface {
	GetList(context.Context, *GetListRequest) (*GetListResponse, error)
	mustEmbedUnimplementedRootLecturerHandlerServer()
}

// UnimplementedRootLecturerHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedRootLecturerHandlerServer struct {
}

func (UnimplementedRootLecturerHandlerServer) GetList(context.Context, *GetListRequest) (*GetListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedRootLecturerHandlerServer) mustEmbedUnimplementedRootLecturerHandlerServer() {}

// UnsafeRootLecturerHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RootLecturerHandlerServer will
// result in compilation errors.
type UnsafeRootLecturerHandlerServer interface {
	mustEmbedUnimplementedRootLecturerHandlerServer()
}

func RegisterRootLecturerHandlerServer(s grpc.ServiceRegistrar, srv RootLecturerHandlerServer) {
	s.RegisterService(&RootLecturerHandler_ServiceDesc, srv)
}

func _RootLecturerHandler_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootLecturerHandlerServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/root_lecturer.RootLecturerHandler/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootLecturerHandlerServer).GetList(ctx, req.(*GetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RootLecturerHandler_ServiceDesc is the grpc.ServiceDesc for RootLecturerHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RootLecturerHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "root_lecturer.RootLecturerHandler",
	HandlerType: (*RootLecturerHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _RootLecturerHandler_GetList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "root/lecturer.proto",
}
