// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: admin/graduation.proto

package graduation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdminGraduationHandlerClient is the client API for AdminGraduationHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminGraduationHandlerClient interface {
	Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error)
	GetListStudent(ctx context.Context, in *GetListStudentRequest, opts ...grpc.CallOption) (*GetListStudentResponse, error)
}

type adminGraduationHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminGraduationHandlerClient(cc grpc.ClientConnInterface) AdminGraduationHandlerClient {
	return &adminGraduationHandlerClient{cc}
}

func (c *adminGraduationHandlerClient) Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error) {
	out := new(ApplyResponse)
	err := c.cc.Invoke(ctx, "/admin_graduation.AdminGraduationHandler/Apply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminGraduationHandlerClient) GetListStudent(ctx context.Context, in *GetListStudentRequest, opts ...grpc.CallOption) (*GetListStudentResponse, error) {
	out := new(GetListStudentResponse)
	err := c.cc.Invoke(ctx, "/admin_graduation.AdminGraduationHandler/GetListStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminGraduationHandlerServer is the server API for AdminGraduationHandler service.
// All implementations must embed UnimplementedAdminGraduationHandlerServer
// for forward compatibility
type AdminGraduationHandlerServer interface {
	Apply(context.Context, *ApplyRequest) (*ApplyResponse, error)
	GetListStudent(context.Context, *GetListStudentRequest) (*GetListStudentResponse, error)
	mustEmbedUnimplementedAdminGraduationHandlerServer()
}

// UnimplementedAdminGraduationHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedAdminGraduationHandlerServer struct {
}

func (UnimplementedAdminGraduationHandlerServer) Apply(context.Context, *ApplyRequest) (*ApplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedAdminGraduationHandlerServer) GetListStudent(context.Context, *GetListStudentRequest) (*GetListStudentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListStudent not implemented")
}
func (UnimplementedAdminGraduationHandlerServer) mustEmbedUnimplementedAdminGraduationHandlerServer() {
}

// UnsafeAdminGraduationHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminGraduationHandlerServer will
// result in compilation errors.
type UnsafeAdminGraduationHandlerServer interface {
	mustEmbedUnimplementedAdminGraduationHandlerServer()
}

func RegisterAdminGraduationHandlerServer(s grpc.ServiceRegistrar, srv AdminGraduationHandlerServer) {
	s.RegisterService(&AdminGraduationHandler_ServiceDesc, srv)
}

func _AdminGraduationHandler_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminGraduationHandlerServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_graduation.AdminGraduationHandler/Apply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminGraduationHandlerServer).Apply(ctx, req.(*ApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminGraduationHandler_GetListStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminGraduationHandlerServer).GetListStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_graduation.AdminGraduationHandler/GetListStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminGraduationHandlerServer).GetListStudent(ctx, req.(*GetListStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminGraduationHandler_ServiceDesc is the grpc.ServiceDesc for AdminGraduationHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminGraduationHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin_graduation.AdminGraduationHandler",
	HandlerType: (*AdminGraduationHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Apply",
			Handler:    _AdminGraduationHandler_Apply_Handler,
		},
		{
			MethodName: "GetListStudent",
			Handler:    _AdminGraduationHandler_GetListStudent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/graduation.proto",
}
