// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: admin/faculty.proto

package faculty

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdminFacultyHandlerClient is the client API for AdminFacultyHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminFacultyHandlerClient interface {
	GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponse, error)
}

type adminFacultyHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminFacultyHandlerClient(cc grpc.ClientConnInterface) AdminFacultyHandlerClient {
	return &adminFacultyHandlerClient{cc}
}

func (c *adminFacultyHandlerClient) GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponse, error) {
	out := new(GetListResponse)
	err := c.cc.Invoke(ctx, "/admin_faculty.AdminFacultyHandler/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminFacultyHandlerServer is the server API for AdminFacultyHandler service.
// All implementations must embed UnimplementedAdminFacultyHandlerServer
// for forward compatibility
type AdminFacultyHandlerServer interface {
	GetList(context.Context, *GetListRequest) (*GetListResponse, error)
	mustEmbedUnimplementedAdminFacultyHandlerServer()
}

// UnimplementedAdminFacultyHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedAdminFacultyHandlerServer struct {
}

func (UnimplementedAdminFacultyHandlerServer) GetList(context.Context, *GetListRequest) (*GetListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedAdminFacultyHandlerServer) mustEmbedUnimplementedAdminFacultyHandlerServer() {}

// UnsafeAdminFacultyHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminFacultyHandlerServer will
// result in compilation errors.
type UnsafeAdminFacultyHandlerServer interface {
	mustEmbedUnimplementedAdminFacultyHandlerServer()
}

func RegisterAdminFacultyHandlerServer(s grpc.ServiceRegistrar, srv AdminFacultyHandlerServer) {
	s.RegisterService(&AdminFacultyHandler_ServiceDesc, srv)
}

func _AdminFacultyHandler_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminFacultyHandlerServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_faculty.AdminFacultyHandler/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminFacultyHandlerServer).GetList(ctx, req.(*GetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminFacultyHandler_ServiceDesc is the grpc.ServiceDesc for AdminFacultyHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminFacultyHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin_faculty.AdminFacultyHandler",
	HandlerType: (*AdminFacultyHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _AdminFacultyHandler_GetList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/faculty.proto",
}
