package handler

import (
	adminAcademicGuidanceHandler "github.com/sccicitb/pupr-backend/handlers/admin/academic_guidance"
	adminAccreditationHandler "github.com/sccicitb/pupr-backend/handlers/admin/accreditation"
	adminAnnouncementHandler "github.com/sccicitb/pupr-backend/handlers/admin/announcement"
	adminAuthenticationHandler "github.com/sccicitb/pupr-backend/handlers/admin/authentication"
	adminBuildingHandler "github.com/sccicitb/pupr-backend/handlers/admin/building"
	adminClassHandler "github.com/sccicitb/pupr-backend/handlers/admin/class"
	adminClassDiscussionHandler "github.com/sccicitb/pupr-backend/handlers/admin/class_discussion"
	adminClassEventHandler "github.com/sccicitb/pupr-backend/handlers/admin/class_event"
	adminClassExamHandler "github.com/sccicitb/pupr-backend/handlers/admin/class_exam"
	adminClassGradeComponentHandler "github.com/sccicitb/pupr-backend/handlers/admin/class_grade_component"
	adminClassMaterialHandler "github.com/sccicitb/pupr-backend/handlers/admin/class_material"
	adminClassWorkHandler "github.com/sccicitb/pupr-backend/handlers/admin/class_work"
	adminCreditQuotaHandler "github.com/sccicitb/pupr-backend/handlers/admin/credit_quota"
	adminCurriculumHandler "github.com/sccicitb/pupr-backend/handlers/admin/curriculum"
	adminDiktiStudyProgramHandler "github.com/sccicitb/pupr-backend/handlers/admin/dikti_study_program"
	adminDocumentActionHandler "github.com/sccicitb/pupr-backend/handlers/admin/document_action"
	adminDocumentTypeHandler "github.com/sccicitb/pupr-backend/handlers/admin/document_type"
	adminExamSupervisorHandler "github.com/sccicitb/pupr-backend/handlers/admin/exam_supervisor"
	adminExamSupervisorRoleHandler "github.com/sccicitb/pupr-backend/handlers/admin/exam_supervisor_role"
	adminExpertiseGroupHandler "github.com/sccicitb/pupr-backend/handlers/admin/expertise_group"
	adminFacultyHandler "github.com/sccicitb/pupr-backend/handlers/admin/faculty"
	adminGradeComponentHandler "github.com/sccicitb/pupr-backend/handlers/admin/grade_component"
	adminGradeTypeHandler "github.com/sccicitb/pupr-backend/handlers/admin/grade_type"
	adminGraduationHandler "github.com/sccicitb/pupr-backend/handlers/admin/graduation"
	adminGraduationPredicateHandler "github.com/sccicitb/pupr-backend/handlers/admin/graduation_predicate"
	adminGraduationSessionHandler "github.com/sccicitb/pupr-backend/handlers/admin/graduation_session"
	adminLearningAchievementHandler "github.com/sccicitb/pupr-backend/handlers/admin/learning_achievement"
	adminLearningAchievementCategoryHandler "github.com/sccicitb/pupr-backend/handlers/admin/learning_achievement_category"
	adminLectureHandler "github.com/sccicitb/pupr-backend/handlers/admin/lecture"
	adminLecturerHandler "github.com/sccicitb/pupr-backend/handlers/admin/lecturer"
	adminLecturerLeaveHandler "github.com/sccicitb/pupr-backend/handlers/admin/lecturer_leave"
	adminLecturerMutationHandler "github.com/sccicitb/pupr-backend/handlers/admin/lecturer_mutation"
	adminLecturerResignationHandler "github.com/sccicitb/pupr-backend/handlers/admin/lecturer_resignation"
	adminLessonPlanHandler "github.com/sccicitb/pupr-backend/handlers/admin/lesson_plan"
	adminMajorHandler "github.com/sccicitb/pupr-backend/handlers/admin/major"
	adminOfficerHandler "github.com/sccicitb/pupr-backend/handlers/admin/officer"
	adminOfficerActionHandler "github.com/sccicitb/pupr-backend/handlers/admin/officer_action"
	adminReportHandler "github.com/sccicitb/pupr-backend/handlers/admin/report"
	adminRoomHandler "github.com/sccicitb/pupr-backend/handlers/admin/room"
	adminSemesterHandler "github.com/sccicitb/pupr-backend/handlers/admin/semester"
	adminSharedFileHandler "github.com/sccicitb/pupr-backend/handlers/admin/shared_file"
	adminStudentHandler "github.com/sccicitb/pupr-backend/handlers/admin/student"
	adminStudentActivityHandler "github.com/sccicitb/pupr-backend/handlers/admin/student_activity"
	adminStudentClassHandler "github.com/sccicitb/pupr-backend/handlers/admin/student_class"
	adminStudentLeaveHandler "github.com/sccicitb/pupr-backend/handlers/admin/student_leave"
	adminStudentSkpiHandler "github.com/sccicitb/pupr-backend/handlers/admin/student_skpi"
	adminStudyLevelHandler "github.com/sccicitb/pupr-backend/handlers/admin/study_level"
	adminStudyPlanHandler "github.com/sccicitb/pupr-backend/handlers/admin/study_plan"
	adminStudyProgramHandler "github.com/sccicitb/pupr-backend/handlers/admin/study_program"
	adminSubjectHandler "github.com/sccicitb/pupr-backend/handlers/admin/subject"
	adminSubjectCategoryHandler "github.com/sccicitb/pupr-backend/handlers/admin/subject_category"
	adminSubjectGradeComponentHandler "github.com/sccicitb/pupr-backend/handlers/admin/subject_grade_component"
	adminThesisHandler "github.com/sccicitb/pupr-backend/handlers/admin/thesis"
	adminThesisExaminerRoleHandler "github.com/sccicitb/pupr-backend/handlers/admin/thesis_examiner_role"
	adminThesisSupervisorRoleHandler "github.com/sccicitb/pupr-backend/handlers/admin/thesis_supervisor_role"
	adminTranscriptHandler "github.com/sccicitb/pupr-backend/handlers/admin/transcript"
	adminYudiciumHandler "github.com/sccicitb/pupr-backend/handlers/admin/yudicium"
	adminYudiciumSessionHandler "github.com/sccicitb/pupr-backend/handlers/admin/yudicium_session"
	adminYudiciumTermHandler "github.com/sccicitb/pupr-backend/handlers/admin/yudicium_term"

	careerStudyProgramHandler "github.com/sccicitb/pupr-backend/handlers/career/study_program"

	generalAuthHandler "github.com/sccicitb/pupr-backend/handlers/general/auth"
	generalFileHandler "github.com/sccicitb/pupr-backend/handlers/general/file"
	generalLocationHandler "github.com/sccicitb/pupr-backend/handlers/general/location"

	lecturerAcademicGuidanceHandler "github.com/sccicitb/pupr-backend/handlers/lecturer/academic_guidance"
	lecturerAnnouncementHandler "github.com/sccicitb/pupr-backend/handlers/lecturer/announcement"
	lecturerClassHandler "github.com/sccicitb/pupr-backend/handlers/lecturer/class"
	lecturerClassAnnouncementHandler "github.com/sccicitb/pupr-backend/handlers/lecturer/class_announcement"
	lecturerClassDiscussionHandler "github.com/sccicitb/pupr-backend/handlers/lecturer/class_discussion"
	lecturerClassEventHandler "github.com/sccicitb/pupr-backend/handlers/lecturer/class_event"
	lecturerClassExamHandler "github.com/sccicitb/pupr-backend/handlers/lecturer/class_exam"
	lecturerClassGradeComponentHandler "github.com/sccicitb/pupr-backend/handlers/lecturer/class_grade_component"
	lecturerClassMaterialHandler "github.com/sccicitb/pupr-backend/handlers/lecturer/class_material"
	lecturerClassWorkHandler "github.com/sccicitb/pupr-backend/handlers/lecturer/class_work"
	lecturerGeneralHandler "github.com/sccicitb/pupr-backend/handlers/lecturer/general"
	lecturerLectureHandler "github.com/sccicitb/pupr-backend/handlers/lecturer/lecture"
	lecturerSemesterHandler "github.com/sccicitb/pupr-backend/handlers/lecturer/semester"
	lecturerSharedFileHandler "github.com/sccicitb/pupr-backend/handlers/lecturer/shared_file"
	lecturerStudyProgramHandler "github.com/sccicitb/pupr-backend/handlers/lecturer/study_program"

	pmbStudentHandler "github.com/sccicitb/pupr-backend/handlers/pmb/student"

	rootAdminHandler "github.com/sccicitb/pupr-backend/handlers/root/admin"
	rootAdminActivityLogHandler "github.com/sccicitb/pupr-backend/handlers/root/admin_activity_log"
	rootDiktiStudyProgramHandler "github.com/sccicitb/pupr-backend/handlers/root/dikti_study_program"
	rootFacultyHandler "github.com/sccicitb/pupr-backend/handlers/root/faculty"
	rootLecturerHandler "github.com/sccicitb/pupr-backend/handlers/root/lecturer"
	rootLecturerStudentActivityLogHandler "github.com/sccicitb/pupr-backend/handlers/root/lecturer_student_activity_log"
	rootMajorHandler "github.com/sccicitb/pupr-backend/handlers/root/major"
	rootPermissionHandler "github.com/sccicitb/pupr-backend/handlers/root/permission"
	rootRoleHandler "github.com/sccicitb/pupr-backend/handlers/root/role"
	rootStudyProgramHandler "github.com/sccicitb/pupr-backend/handlers/root/study_program"

	excelHandler "github.com/sccicitb/pupr-backend/handlers/admin/excel"
	studentAcademicGuidanceHandler "github.com/sccicitb/pupr-backend/handlers/student/academic_guidance"
	studentAnnouncementHandler "github.com/sccicitb/pupr-backend/handlers/student/announcement"
	studentClassHandler "github.com/sccicitb/pupr-backend/handlers/student/class"
	studentClassAnnouncementHandler "github.com/sccicitb/pupr-backend/handlers/student/class_announcement"
	studentClassDiscussionHandler "github.com/sccicitb/pupr-backend/handlers/student/class_discussion"
	studentClassEventHandler "github.com/sccicitb/pupr-backend/handlers/student/class_event"
	studentClassExamHandler "github.com/sccicitb/pupr-backend/handlers/student/class_exam"
	studentClassMaterialHandler "github.com/sccicitb/pupr-backend/handlers/student/class_material"
	studentClassWorkHandler "github.com/sccicitb/pupr-backend/handlers/student/class_work"
	studentGeneralHandler "github.com/sccicitb/pupr-backend/handlers/student/general"
	studentGradeTypeHandler "github.com/sccicitb/pupr-backend/handlers/student/grade_type"
	studentLectureHandler "github.com/sccicitb/pupr-backend/handlers/student/lecture"
	studentSemesterHandler "github.com/sccicitb/pupr-backend/handlers/student/semester"
	studentSharedFileHandler "github.com/sccicitb/pupr-backend/handlers/student/shared_file"
	studentStudentLeaveHandler "github.com/sccicitb/pupr-backend/handlers/student/student_leave"
	studentStudentSkpiHandler "github.com/sccicitb/pupr-backend/handlers/student/student_skpi"
	studentStudyPlanHandler "github.com/sccicitb/pupr-backend/handlers/student/study_plan"
	studentThesisHandler "github.com/sccicitb/pupr-backend/handlers/student/thesis"
	studentTranscriptHandler "github.com/sccicitb/pupr-backend/handlers/student/transcript"
)

type HandlerCtx struct {
	AdminAcademicGuidanceHandler            adminAcademicGuidanceHandler.AdminAcademicGuidanceHandlerInterface
	AdminAccreditationHandler               adminAccreditationHandler.AdminAccreditationHandlerInterface
	AdminAnnouncementHandler                adminAnnouncementHandler.AdminAnnouncementHandlerInterface
	AdminAuthenticationHandler              adminAuthenticationHandler.AdminAuthenticationHandlerInterface
	AdminBuildingHandler                    adminBuildingHandler.AdminBuildingHandlerInterface
	AdminClassHandler                       adminClassHandler.AdminClassHandlerInterface
	AdminClassDiscussionHandler             adminClassDiscussionHandler.AdminClassDiscussionHandlerInterface
	AdminClassEventHandler                  adminClassEventHandler.AdminClassEventHandlerInterface
	AdminClassExamHandler                   adminClassExamHandler.AdminClassExamHandlerInterface
	AdminClassGradeComponentHandler         adminClassGradeComponentHandler.AdminClassGradeComponentHandlerInterface
	AdminClassMaterialHandler               adminClassMaterialHandler.AdminClassMaterialHandlerInterface
	AdminClassWorkHandler                   adminClassWorkHandler.AdminClassWorkHandlerInterface
	AdminCreditQuotaHandler                 adminCreditQuotaHandler.AdminCreditQuotaHandlerInterface
	AdminCurriculumHandler                  adminCurriculumHandler.AdminCurriculumHandlerInterface
	AdminDiktiStudyProgramHandler           adminDiktiStudyProgramHandler.AdminDiktiStudyProgramHandlerInterface
	AdminDocumentActionHandler              adminDocumentActionHandler.AdminDocumentActionHandlerInterface
	AdminDocumentTypeHandler                adminDocumentTypeHandler.AdminDocumentTypeHandlerInterface
	AdminExamSupervisorHandler              adminExamSupervisorHandler.AdminExamSupervisorHandlerInterface
	AdminExamSupervisorRoleHandler          adminExamSupervisorRoleHandler.AdminExamSupervisorRoleHandlerInterface
	AdminExpertiseGroupHandler              adminExpertiseGroupHandler.AdminExpertiseGroupHandlerInterface
	AdminFacultyHandler                     adminFacultyHandler.AdminFacultyHandlerInterface
	AdminGradeComponentHandler              adminGradeComponentHandler.AdminGradeComponentHandlerInterface
	AdminGradeTypeHandler                   adminGradeTypeHandler.AdminGradeTypeHandlerInterface
	AdminGraduationHandler                  adminGraduationHandler.AdminGraduationHandlerInterface
	AdminGraduationPredicateHandler         adminGraduationPredicateHandler.AdminGraduationPredicateHandlerInterface
	AdminGraduationSessionHandler           adminGraduationSessionHandler.AdminGraduationSessionHandlerInterface
	AdminLearningAchievementHandler         adminLearningAchievementHandler.AdminLearningAchievementHandlerInterface
	AdminLearningAchievementCategoryHandler adminLearningAchievementCategoryHandler.AdminLearningAchievementCategoryHandlerInterface
	AdminLecturerHandler                    adminLecturerHandler.AdminLecturerHandlerInterface
	AdminLectureHandler                     adminLectureHandler.AdminLectureHandlerInterface
	AdminLecturerLeaveHandler               adminLecturerLeaveHandler.AdminLecturerLeaveHandlerInterface
	AdminLecturerMutationHandler            adminLecturerMutationHandler.AdminLecturerMutationHandlerInterface
	AdminLecturerResignationHandler         adminLecturerResignationHandler.AdminLecturerResignationHandlerInterface
	AdminLessonPlanHandler                  adminLessonPlanHandler.AdminLessonPlanHandlerInterface
	AdminMajorHandler                       adminMajorHandler.AdminMajorHandlerInterface
	AdminOfficerHandler                     adminOfficerHandler.AdminOfficerHandlerInterface
	AdminOfficerActionHandler               adminOfficerActionHandler.AdminOfficerActionHandlerInterface
	AdminReportHandler                      adminReportHandler.AdminReportHandlerInterface
	AdminRoomHandler                        adminRoomHandler.AdminRoomHandlerInterface
	AdminSemesterHandler                    adminSemesterHandler.AdminSemesterHandlerInterface
	AdminSharedFileHandler                  adminSharedFileHandler.AdminSharedFileHandlerInterface
	AdminStudentHandler                     adminStudentHandler.AdminStudentHandlerInterface
	AdminStudentActivityHandler             adminStudentActivityHandler.AdminStudentActivityHandlerInterface
	AdminStudentClassHandler                adminStudentClassHandler.AdminStudentClassHandlerInterface
	AdminStudentLeaveHandler                adminStudentLeaveHandler.AdminStudentLeaveHandlerInterface
	AdminStudentSkpiHandler                 adminStudentSkpiHandler.AdminStudentSkpiHandlerInterface
	AdminStudyLevelHandler                  adminStudyLevelHandler.AdminStudyLevelHandlerInterface
	AdminStudyPlanHandler                   adminStudyPlanHandler.AdminStudyPlanHandlerInterface
	AdminStudyProgramHandler                adminStudyProgramHandler.AdminStudyProgramHandlerInterface
	AdminSubjectHandler                     adminSubjectHandler.AdminSubjectHandlerInterface
	AdminSubjectCategoryHandler             adminSubjectCategoryHandler.AdminSubjectCategoryHandlerInterface
	AdminSubjectGradeComponentHandler       adminSubjectGradeComponentHandler.AdminSubjectGradeComponentHandlerInterface
	AdminThesisHandler                      adminThesisHandler.AdminThesisHandlerInterface
	AdminThesisExaminerRoleHandler          adminThesisExaminerRoleHandler.AdminThesisExaminerRoleHandlerInterface
	AdminThesisSupervisorRoleHandler        adminThesisSupervisorRoleHandler.AdminThesisSupervisorRoleHandlerInterface
	AdminTranscriptHandler                  adminTranscriptHandler.AdminTranscriptHandlerInterface
	AdminYudiciumSessionHandler             adminYudiciumSessionHandler.AdminYudiciumSessionHandlerInterface
	AdminYudiciumHandler                    adminYudiciumHandler.AdminYudiciumHandlerInterface
	AdminYudiciumTermHandler                adminYudiciumTermHandler.AdminYudiciumTermHandlerInterface

	CareerStudyProgramHandler careerStudyProgramHandler.CareerStudyProgramHandlerInterface

	GeneralAuthHandler     generalAuthHandler.GeneralAuthHandlerInterface
	GeneralFileHandler     generalFileHandler.GeneralFileHandlerInterface
	GeneralLocationHandler generalLocationHandler.GeneralLocationHandlerInterface

	LecturerAcademicGuidanceHandler    lecturerAcademicGuidanceHandler.LecturerAcademicGuidanceHandlerInterface
	LecturerAnnouncementHandler        lecturerAnnouncementHandler.LecturerAnnouncementHandlerInterface
	LecturerClassHandler               lecturerClassHandler.LecturerClassHandlerInterface
	LecturerClassAnnouncementHandler   lecturerClassAnnouncementHandler.LecturerClassAnnouncementHandlerInterface
	LecturerClassDiscussionHandler     lecturerClassDiscussionHandler.LecturerClassDiscussionHandlerInterface
	LecturerClassEventHandler          lecturerClassEventHandler.LecturerClassEventHandlerInterface
	LecturerClassExamHandler           lecturerClassExamHandler.LecturerClassExamHandlerInterface
	LecturerClassGradeComponentHandler lecturerClassGradeComponentHandler.LecturerClassGradeComponentHandlerInterface
	LecturerClassMaterialHandler       lecturerClassMaterialHandler.LecturerClassMaterialHandlerInterface
	LecturerClassWorkHandler           lecturerClassWorkHandler.LecturerClassWorkHandlerInterface
	LecturerGeneralHandler             lecturerGeneralHandler.LecturerGeneralHandlerInterface
	LecturerLectureHandler             lecturerLectureHandler.LecturerLectureHandlerInterface
	LecturerSemesterHandler            lecturerSemesterHandler.LecturerSemesterHandlerInterface
	LecturerSharedFileHandler          lecturerSharedFileHandler.LecturerSharedFileHandlerInterface
	LecturerStudyProgramHandler        lecturerStudyProgramHandler.LecturerStudyProgramHandlerInterface

	PmbStudentHandler pmbStudentHandler.PmbStudentHandlerInterface

	RootAdminHandler                      rootAdminHandler.RootAdminHandlerInterface
	RootAdminActivityLogHandler           rootAdminActivityLogHandler.RootAdminActivityLogHandlerInterface
	RootDiktiStudyProgramHandler          rootDiktiStudyProgramHandler.RootDiktiStudyProgramHandlerInterface
	RootFacultyHandler                    rootFacultyHandler.RootFacultyHandlerInterface
	RootLecturerHandler                   rootLecturerHandler.RootLecturerHandlerInterface
	RootLecturerStudentActivityLogHandler rootLecturerStudentActivityLogHandler.RootLecturerStudentActivityLogHandlerInterface
	RootMajorHandler                      rootMajorHandler.RootMajorHandlerInterface
	RootPermissionHandler                 rootPermissionHandler.RootPermissionHandlerInterface
	RootRoleHandler                       rootRoleHandler.RootRoleHandlerInterface
	RootStudyProgramHandler               rootStudyProgramHandler.RootStudyProgramHandlerInterface

	StudentAcademicGuidanceHandler  studentAcademicGuidanceHandler.StudentAcademicGuidanceHandlerInterface
	StudentAnnouncementHandler      studentAnnouncementHandler.StudentAnnouncementHandlerInterface
	StudentClassHandler             studentClassHandler.StudentClassHandlerInterface
	StudentClassAnnouncementHandler studentClassAnnouncementHandler.StudentClassAnnouncementHandlerInterface
	StudentClassDiscussionHandler   studentClassDiscussionHandler.StudentClassDiscussionHandlerInterface
	StudentClassEventHandler        studentClassEventHandler.StudentClassEventHandlerInterface
	StudentClassExamHandler         studentClassExamHandler.StudentClassExamHandlerInterface
	StudentClassMaterialHandler     studentClassMaterialHandler.StudentClassMaterialHandlerInterface
	StudentClassWorkHandler         studentClassWorkHandler.StudentClassWorkHandlerInterface
	StudentGeneralHandler           studentGeneralHandler.StudentGeneralHandlerInterface
	StudentGradeTypeHandler         studentGradeTypeHandler.StudentGradeTypeHandlerInterface
	StudentLectureHandler           studentLectureHandler.StudentLectureHandlerInterface
	StudentSemesterHandler          studentSemesterHandler.StudentSemesterHandlerInterface
	StudentSharedFileHandler        studentSharedFileHandler.StudentSharedFileHandlerInterface
	StudentStudentLeaveHandler      studentStudentLeaveHandler.StudentStudentLeaveHandlerInterface
	StudentStudentSkpiHandler       studentStudentSkpiHandler.StudentStudentSkpiHandlerInterface
	StudentStudyPlanHandler         studentStudyPlanHandler.StudentStudyPlanHandlerInterface
	StudentThesisHandler            studentThesisHandler.StudentThesisHandlerInterface
	StudentTranscriptHandler        studentTranscriptHandler.StudentTranscriptHandlerInterface
	ExcelHandler                    excelHandler.ExcelHandlerInterface
}
