package routers

import (
	"fmt"
	"net/http"

	"github.com/gorilla/mux"
	"github.com/sccicitb/pupr-backend/config"
	appConstants "github.com/sccicitb/pupr-backend/constants"
	"github.com/sccicitb/pupr-backend/infra/context/handler"
	"github.com/sccicitb/pupr-backend/infra/middleware"
)

// InitialRouter for object routers
func InitialRouter(handlerCtx *handler.HandlerCtx, mw middleware.MiddlewareInterface, cfg *config.Config) *mux.Router {
	r := mux.NewRouter()

	if cfg.Server.LocalStoragePath != "" {
		staticPath := fmt.Sprintf("/%s", cfg.Server.LocalStoragePath)
		fs := http.FileServer(http.Dir(cfg.Server.LocalStoragePath))
		r.PathPrefix(staticPath).Handler(http.StripPrefix(staticPath, fs))
	}

	s := r.PathPrefix("/api/v1").Subrouter()
	s.HandleFunc("/general_auth.GeneralAuthHandler/GetSsoAuth", handlerCtx.GeneralAuthHandler.GetSsoAuth).Methods(http.MethodGet)
	s.HandleFunc("/general_auth.GeneralAuthHandler/Login", handlerCtx.GeneralAuthHandler.Login).Methods(http.MethodPost)
	s.HandleFunc("/general_auth.GeneralAuthHandler/LoginWithSso", handlerCtx.GeneralAuthHandler.LoginWithSso).Methods(http.MethodPost)

	// TODO::remove temp
	s.HandleFunc("/general_location.GeneralLocationHandler/TempCreateData", handlerCtx.GeneralLocationHandler.TempCreateData).Methods(http.MethodPost)
	s.HandleFunc("/general_location.GeneralLocationHandler/TempGetData", handlerCtx.GeneralLocationHandler.TempGetData).Methods(http.MethodGet)

	// Admin Handler

	admin := s.PathPrefix("/admin").Subrouter()
	admin.Use(mw.AdminAccessToken)
	admin.HandleFunc("/admin_accreditation.AdminAccreditationHandler/GetList", handlerCtx.AdminAccreditationHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_announcement.AdminAnnouncementHandler/GetList", handlerCtx.AdminAnnouncementHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_building.AdminBuildingHandler/GetList", handlerCtx.AdminBuildingHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_class.AdminClassHandler/GetList", handlerCtx.AdminClassHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_class_discussion.AdminClassDiscussionHandler/GetList", handlerCtx.AdminClassDiscussionHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_class_event.AdminClassEventHandler/GetList", handlerCtx.AdminClassEventHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_class_exam.AdminClassExamHandler/GetList", handlerCtx.AdminClassExamHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_class_grade_component.AdminClassGradeComponentHandler/GetList", handlerCtx.AdminClassGradeComponentHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_class_material.AdminClassMaterialHandler/GetList", handlerCtx.AdminClassMaterialHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_class_work.AdminClassWorkHandler/GetList", handlerCtx.AdminClassWorkHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_credit_quota.AdminCreditQuotaHandler/GetList", handlerCtx.AdminCreditQuotaHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_curriculum.AdminCurriculumHandler/GetList", handlerCtx.AdminCurriculumHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_dikti_study_program.AdminDiktiStudyProgramHandler/GetList", handlerCtx.AdminDiktiStudyProgramHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_document_action.AdminDocumentActionHandler/GetList", handlerCtx.AdminDocumentActionHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_document_type.AdminDocumentTypeHandler/GetList", handlerCtx.AdminDocumentTypeHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_exam_supervisor.AdminExamSupervisorHandler/GetList", handlerCtx.AdminExamSupervisorHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_exam_supervisor_role.AdminExamSupervisorRoleHandler/GetList", handlerCtx.AdminExamSupervisorRoleHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_expertise_group.AdminExpertiseGroupHandler/GetList", handlerCtx.AdminExpertiseGroupHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_faculty.AdminFacultyHandler/GetList", handlerCtx.AdminFacultyHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_grade_component.AdminGradeComponentHandler/GetList", handlerCtx.AdminGradeComponentHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_grade_type.AdminGradeTypeHandler/GetList", handlerCtx.AdminGradeTypeHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_graduation_predicate.AdminGraduationPredicateHandler/GetList", handlerCtx.AdminGraduationPredicateHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_graduation_session.AdminGraduationSessionHandler/GetList", handlerCtx.AdminGraduationSessionHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_learning_achievement.AdminLearningAchievementHandler/GetList", handlerCtx.AdminLearningAchievementHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_learning_achievement_category.AdminLearningAchievementCategoryHandler/GetList", handlerCtx.AdminLearningAchievementCategoryHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_lecture.AdminLectureHandler/GetCalendar", handlerCtx.AdminLectureHandler.GetCalendar).Methods(http.MethodGet)
	admin.HandleFunc("/admin_lecture.AdminLectureHandler/GetList", handlerCtx.AdminLectureHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_lecturer.AdminLecturerHandler/GetList", handlerCtx.AdminLecturerHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_lecturer_leave.AdminLecturerLeaveHandler/GetList", handlerCtx.AdminLecturerLeaveHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_lecturer_mutation.AdminLecturerMutationHandler/GetList", handlerCtx.AdminLecturerMutationHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_lecturer_resignation.AdminLecturerResignationHandler/GetList", handlerCtx.AdminLecturerResignationHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_lesson_plan.AdminLessonPlanHandler/GetList", handlerCtx.AdminLessonPlanHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_major.AdminMajorHandler/GetList", handlerCtx.AdminMajorHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_officer.AdminOfficerHandler/GetList", handlerCtx.AdminOfficerHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_officer_action.AdminOfficerActionHandler/GetList", handlerCtx.AdminOfficerActionHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_room.AdminRoomHandler/GetList", handlerCtx.AdminRoomHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_semester.AdminSemesterHandler/GetList", handlerCtx.AdminSemesterHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_shared_file.AdminSharedFileHandler/GetList", handlerCtx.AdminSharedFileHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_student.AdminStudentHandler/GetList", handlerCtx.AdminStudentHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_student_activity.AdminStudentActivityHandler/GetList", handlerCtx.AdminStudentActivityHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_student_skpi.AdminStudentSkpiHandler/GetList", handlerCtx.AdminStudentSkpiHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_student_class.AdminStudentClassHandler/GetList", handlerCtx.AdminStudentClassHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_study_level.AdminStudyLevelHandler/GetList", handlerCtx.AdminStudyLevelHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_study_plan.AdminStudyPlanHandler/GetList", handlerCtx.AdminStudyPlanHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_study_program.AdminStudyProgramHandler/GetList", handlerCtx.AdminStudyProgramHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_subject_category.AdminSubjectCategoryHandler/GetList", handlerCtx.AdminSubjectCategoryHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_subject.AdminSubjectHandler/GetList", handlerCtx.AdminSubjectHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_subject_grade_component.AdminSubjectGradeComponentHandler/GetList", handlerCtx.AdminSubjectGradeComponentHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_thesis.AdminThesisHandler/GetList", handlerCtx.AdminThesisHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_thesis.AdminThesisHandler/GetListThesisDefenseRequest", handlerCtx.AdminThesisHandler.GetListThesisDefenseRequest).Methods(http.MethodGet)
	admin.HandleFunc("/admin_thesis_examiner_role.AdminThesisExaminerRoleHandler/GetList", handlerCtx.AdminThesisExaminerRoleHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_thesis_supervisor_role.AdminThesisSupervisorRoleHandler/GetList", handlerCtx.AdminThesisSupervisorRoleHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_yudicium_session.AdminYudiciumSessionHandler/GetList", handlerCtx.AdminYudiciumSessionHandler.GetList).Methods(http.MethodGet)
	admin.HandleFunc("/admin_yudicium_term.AdminYudiciumTermHandler/GetList", handlerCtx.AdminYudiciumTermHandler.GetList).Methods(http.MethodGet)

	auth := admin.PathPrefix("/auth").Subrouter()
	auth.Use(appConstants.PermissionPortalAkademikMiddleware, mw.PermissionMiddleware)
	auth.HandleFunc("/admin_authentication.AdminAuthenticationHandler/GetDetail", handlerCtx.AdminAuthenticationHandler.GetDetail).Methods(http.MethodGet)
	auth.HandleFunc("/admin_authentication.AdminAuthenticationHandler/Create", handlerCtx.AdminAuthenticationHandler.Create).Methods(http.MethodPost)
	auth.HandleFunc("/admin_authentication.AdminAuthenticationHandler/BulkCreate", handlerCtx.AdminAuthenticationHandler.BulkCreate).Methods(http.MethodPost)
	auth.HandleFunc("/admin_authentication.AdminAuthenticationHandler/Update", handlerCtx.AdminAuthenticationHandler.Update).Methods(http.MethodPatch)
	auth.HandleFunc("/admin_authentication.AdminAuthenticationHandler/Delete", handlerCtx.AdminAuthenticationHandler.Delete).Methods(http.MethodDelete)
	auth.HandleFunc("/admin_authentication.AdminAuthenticationHandler/UpdatePassword", handlerCtx.AdminAuthenticationHandler.UpdatePassword).Methods(http.MethodPatch)

	creditQuota := admin.PathPrefix("/credit_quota").Subrouter()
	creditQuota.Use(appConstants.PermissionJatahSksMiddleware, mw.PermissionMiddleware)
	creditQuota.HandleFunc("/admin_credit_quota.AdminCreditQuotaHandler/Create", handlerCtx.AdminCreditQuotaHandler.Create).Methods(http.MethodPost)
	creditQuota.HandleFunc("/admin_credit_quota.AdminCreditQuotaHandler/Update", handlerCtx.AdminCreditQuotaHandler.Update).Methods(http.MethodPatch)
	creditQuota.HandleFunc("/admin_credit_quota.AdminCreditQuotaHandler/Delete", handlerCtx.AdminCreditQuotaHandler.Delete).Methods(http.MethodDelete)

	curriculum := admin.PathPrefix("/curriculum").Subrouter()
	curriculum.Use(appConstants.PermissionKurikulumMiddleware, mw.PermissionMiddleware)
	curriculum.HandleFunc("/admin_curriculum.AdminCurriculumHandler/GetDetail", handlerCtx.AdminCurriculumHandler.GetDetail).Methods(http.MethodGet)
	curriculum.HandleFunc("/admin_curriculum.AdminCurriculumHandler/GetActiveByStudyProgramId", handlerCtx.AdminCurriculumHandler.GetActiveByStudyProgramId).Methods(http.MethodGet)
	curriculum.HandleFunc("/admin_curriculum.AdminCurriculumHandler/Create", handlerCtx.AdminCurriculumHandler.Create).Methods(http.MethodPost)
	curriculum.HandleFunc("/admin_curriculum.AdminCurriculumHandler/Update", handlerCtx.AdminCurriculumHandler.Update).Methods(http.MethodPatch)
	curriculum.HandleFunc("/admin_curriculum.AdminCurriculumHandler/Delete", handlerCtx.AdminCurriculumHandler.Delete).Methods(http.MethodDelete)
	curriculum.HandleFunc("/admin_subject.AdminSubjectHandler/GetDetail", handlerCtx.AdminSubjectHandler.GetDetail).Methods(http.MethodGet)
	curriculum.HandleFunc("/admin_subject.AdminSubjectHandler/Create", handlerCtx.AdminSubjectHandler.Create).Methods(http.MethodPost)
	curriculum.HandleFunc("/admin_subject.AdminSubjectHandler/Update", handlerCtx.AdminSubjectHandler.Update).Methods(http.MethodPatch)
	curriculum.HandleFunc("/admin_subject.AdminSubjectHandler/Delete", handlerCtx.AdminSubjectHandler.Delete).Methods(http.MethodDelete)
	curriculum.HandleFunc("/admin_subject.AdminSubjectHandler/SetPrerequisiteSubject", handlerCtx.AdminSubjectHandler.SetPrerequisiteSubject).Methods(http.MethodPatch)
	curriculum.HandleFunc("/admin_subject.AdminSubjectHandler/SetEquivalentSubject", handlerCtx.AdminSubjectHandler.SetEquivalentSubject).Methods(http.MethodPatch)
	curriculum.HandleFunc("/admin_subject.AdminSubjectHandler/DeleteEquivalentSubject", handlerCtx.AdminSubjectHandler.DeleteEquivalentSubject).Methods(http.MethodDelete)
	curriculum.HandleFunc("/admin_lesson_plan.AdminLessonPlanHandler/Create", handlerCtx.AdminLessonPlanHandler.Create).Methods(http.MethodPost)
	curriculum.HandleFunc("/admin_lesson_plan.AdminLessonPlanHandler/Update", handlerCtx.AdminLessonPlanHandler.Update).Methods(http.MethodPatch)
	curriculum.HandleFunc("/admin_lesson_plan.AdminLessonPlanHandler/Delete", handlerCtx.AdminLessonPlanHandler.Delete).Methods(http.MethodDelete)

	gradeInput := admin.PathPrefix("/grade_input").Subrouter()
	gradeInput.Use(appConstants.PermissionInputNilaiMiddleware, mw.PermissionMiddleware)
	gradeInput.HandleFunc("/admin_student_class.AdminStudentClassHandler/BulkGradeStudentClass", handlerCtx.AdminStudentClassHandler.BulkGradeStudentClass).Methods(http.MethodPost)

	gradeComponent := admin.PathPrefix("/grade_component").Subrouter()
	gradeComponent.Use(appConstants.PermissionKomponenNilaiMiddleware, mw.PermissionMiddleware)
	gradeComponent.HandleFunc("/admin_grade_component.AdminGradeComponentHandler/Create", handlerCtx.AdminGradeComponentHandler.Create).Methods(http.MethodPost)
	gradeComponent.HandleFunc("/admin_grade_component.AdminGradeComponentHandler/Update", handlerCtx.AdminGradeComponentHandler.Update).Methods(http.MethodPatch)
	gradeComponent.HandleFunc("/admin_grade_component.AdminGradeComponentHandler/Delete", handlerCtx.AdminGradeComponentHandler.Delete).Methods(http.MethodDelete)
	gradeComponent.HandleFunc("/admin_grade_component.AdminGradeComponentHandler/GetListBySubjectCategory", handlerCtx.AdminGradeComponentHandler.GetListBySubjectCategory).Methods(http.MethodGet)
	gradeComponent.HandleFunc("/admin_grade_component.AdminGradeComponentHandler/BulkUpdatePercentage", handlerCtx.AdminGradeComponentHandler.BulkUpdatePercentage).Methods(http.MethodPatch)
	gradeComponent.HandleFunc("/admin_subject_grade_component.AdminSubjectGradeComponentHandler/Set", handlerCtx.AdminSubjectGradeComponentHandler.Set).Methods(http.MethodPatch)
	gradeComponent.HandleFunc("/admin_class_grade_component.AdminClassGradeComponentHandler/Set", handlerCtx.AdminClassGradeComponentHandler.Set).Methods(http.MethodPatch)

	gradeType := admin.PathPrefix("/grade_type").Subrouter()
	gradeType.Use(appConstants.PermissionJenisNilaiMiddleware, mw.PermissionMiddleware)
	gradeType.HandleFunc("/admin_grade_type.AdminGradeTypeHandler/Create", handlerCtx.AdminGradeTypeHandler.Create).Methods(http.MethodPost)
	gradeType.HandleFunc("/admin_grade_type.AdminGradeTypeHandler/Update", handlerCtx.AdminGradeTypeHandler.Update).Methods(http.MethodPatch)
	gradeType.HandleFunc("/admin_grade_type.AdminGradeTypeHandler/Delete", handlerCtx.AdminGradeTypeHandler.Delete).Methods(http.MethodDelete)

	graduation := admin.PathPrefix("/graduation").Subrouter()
	graduation.Use(appConstants.PermissionKelulusanMiddleware, mw.PermissionMiddleware)
	graduation.HandleFunc("/admin_study_program.AdminStudyProgramHandler/UpdateDegree", handlerCtx.AdminStudyProgramHandler.UpdateDegree).Methods(http.MethodPatch)
	graduation.HandleFunc("/admin_yudicium_term.AdminYudiciumTermHandler/Create", handlerCtx.AdminYudiciumTermHandler.Create).Methods(http.MethodPost)
	graduation.HandleFunc("/admin_yudicium_term.AdminYudiciumTermHandler/Update", handlerCtx.AdminYudiciumTermHandler.Update).Methods(http.MethodPatch)
	graduation.HandleFunc("/admin_yudicium_term.AdminYudiciumTermHandler/Delete", handlerCtx.AdminYudiciumTermHandler.Delete).Methods(http.MethodDelete)
	graduation.HandleFunc("/admin_yudicium_session.AdminYudiciumSessionHandler/Create", handlerCtx.AdminYudiciumSessionHandler.Create).Methods(http.MethodPost)
	graduation.HandleFunc("/admin_yudicium_session.AdminYudiciumSessionHandler/Update", handlerCtx.AdminYudiciumSessionHandler.Update).Methods(http.MethodPatch)
	graduation.HandleFunc("/admin_yudicium_session.AdminYudiciumSessionHandler/Delete", handlerCtx.AdminYudiciumSessionHandler.Delete).Methods(http.MethodDelete)
	graduation.HandleFunc("/admin_yudicium.AdminYudiciumHandler/Apply", handlerCtx.AdminYudiciumHandler.Apply).Methods(http.MethodPost)
	graduation.HandleFunc("/admin_yudicium.AdminYudiciumHandler/GetListStudent", handlerCtx.AdminYudiciumHandler.GetListStudent).Methods(http.MethodGet)
	graduation.HandleFunc("/admin_yudicium.AdminYudiciumHandler/Do", handlerCtx.AdminYudiciumHandler.Do).Methods(http.MethodPost)
	graduation.HandleFunc("/admin_graduation_session.AdminGraduationSessionHandler/Create", handlerCtx.AdminGraduationSessionHandler.Create).Methods(http.MethodPost)
	graduation.HandleFunc("/admin_graduation_session.AdminGraduationSessionHandler/Update", handlerCtx.AdminGraduationSessionHandler.Update).Methods(http.MethodPatch)
	graduation.HandleFunc("/admin_graduation_session.AdminGraduationSessionHandler/Delete", handlerCtx.AdminGraduationSessionHandler.Delete).Methods(http.MethodDelete)
	graduation.HandleFunc("/admin_graduation.AdminGraduationHandler/Apply", handlerCtx.AdminGraduationHandler.Apply).Methods(http.MethodPost)
	graduation.HandleFunc("/admin_graduation.AdminGraduationHandler/GetListStudent", handlerCtx.AdminGraduationHandler.GetListStudent).Methods(http.MethodGet)

	graduationPredicate := admin.PathPrefix("/graduation_predicate").Subrouter()
	graduationPredicate.Use(appConstants.PermissionPredikatKelulusanMiddleware, mw.PermissionMiddleware)
	graduationPredicate.HandleFunc("/admin_graduation_predicate.AdminGraduationPredicateHandler/Create", handlerCtx.AdminGraduationPredicateHandler.Create).Methods(http.MethodPost)
	graduationPredicate.HandleFunc("/admin_graduation_predicate.AdminGraduationPredicateHandler/Update", handlerCtx.AdminGraduationPredicateHandler.Update).Methods(http.MethodPatch)
	graduationPredicate.HandleFunc("/admin_graduation_predicate.AdminGraduationPredicateHandler/Delete", handlerCtx.AdminGraduationPredicateHandler.Delete).Methods(http.MethodDelete)

	adminLecturer := admin.PathPrefix("/lecturer").Subrouter()
	adminLecturer.Use(appConstants.PermissionDosenMiddleware, mw.PermissionMiddleware)
	adminLecturer.HandleFunc("/admin_lecturer.AdminLecturerHandler/GetDetail", handlerCtx.AdminLecturerHandler.GetDetail).Methods(http.MethodGet)
	adminLecturer.HandleFunc("/admin_lecturer.AdminLecturerHandler/Create", handlerCtx.AdminLecturerHandler.Create).Methods(http.MethodPost)
	adminLecturer.HandleFunc("/admin_lecturer.AdminLecturerHandler/Update", handlerCtx.AdminLecturerHandler.Update).Methods(http.MethodPatch)
	adminLecturer.HandleFunc("/admin_lecturer.AdminLecturerHandler/Delete", handlerCtx.AdminLecturerHandler.Delete).Methods(http.MethodDelete)
	adminLecturer.HandleFunc("/admin_lecturer.AdminLecturerHandler/GetSchedule", handlerCtx.AdminLecturerHandler.GetSchedule).Methods(http.MethodGet)
	adminLecturer.HandleFunc("/admin_academic_guidance.AdminAcademicGuidanceHandler/GetListStudent", handlerCtx.AdminAcademicGuidanceHandler.GetListStudent).Methods(http.MethodGet)
	adminLecturer.HandleFunc("/admin_academic_guidance.AdminAcademicGuidanceHandler/UpsertDecision", handlerCtx.AdminAcademicGuidanceHandler.UpsertDecision).Methods(http.MethodPost)
	adminLecturer.HandleFunc("/admin_academic_guidance.AdminAcademicGuidanceHandler/GetSessionList", handlerCtx.AdminAcademicGuidanceHandler.GetSessionList).Methods(http.MethodGet)
	adminLecturer.HandleFunc("/admin_academic_guidance.AdminAcademicGuidanceHandler/CreateSession", handlerCtx.AdminAcademicGuidanceHandler.CreateSession).Methods(http.MethodPost)
	adminLecturer.HandleFunc("/admin_academic_guidance.AdminAcademicGuidanceHandler/UpdateSession", handlerCtx.AdminAcademicGuidanceHandler.UpdateSession).Methods(http.MethodPatch)
	adminLecturer.HandleFunc("/admin_academic_guidance.AdminAcademicGuidanceHandler/DeleteSession", handlerCtx.AdminAcademicGuidanceHandler.DeleteSession).Methods(http.MethodDelete)
	adminLecturer.HandleFunc("/admin_lecturer_leave.AdminLecturerLeaveHandler/Create", handlerCtx.AdminLecturerLeaveHandler.Create).Methods(http.MethodPost)
	adminLecturer.HandleFunc("/admin_lecturer_leave.AdminLecturerLeaveHandler/Update", handlerCtx.AdminLecturerLeaveHandler.Update).Methods(http.MethodPatch)
	adminLecturer.HandleFunc("/admin_lecturer_leave.AdminLecturerLeaveHandler/End", handlerCtx.AdminLecturerLeaveHandler.End).Methods(http.MethodPatch)
	adminLecturer.HandleFunc("/admin_lecturer_resignation.AdminLecturerResignationHandler/Create", handlerCtx.AdminLecturerResignationHandler.Create).Methods(http.MethodPost)
	adminLecturer.HandleFunc("/admin_lecturer_mutation.AdminLecturerMutationHandler/Create", handlerCtx.AdminLecturerMutationHandler.Create).Methods(http.MethodPost)

	officer := admin.PathPrefix("/officer").Subrouter()
	officer.Use(appConstants.PermissionPejabatMiddleware, mw.PermissionMiddleware)
	officer.HandleFunc("/admin_document_action.AdminDocumentActionHandler/Create", handlerCtx.AdminDocumentActionHandler.Create).Methods(http.MethodPost)
	officer.HandleFunc("/admin_document_action.AdminDocumentActionHandler/Update", handlerCtx.AdminDocumentActionHandler.Update).Methods(http.MethodPatch)
	officer.HandleFunc("/admin_document_action.AdminDocumentActionHandler/Delete", handlerCtx.AdminDocumentActionHandler.Delete).Methods(http.MethodDelete)
	officer.HandleFunc("/admin_document_type.AdminDocumentTypeHandler/Create", handlerCtx.AdminDocumentTypeHandler.Create).Methods(http.MethodPost)
	officer.HandleFunc("/admin_document_type.AdminDocumentTypeHandler/Update", handlerCtx.AdminDocumentTypeHandler.Update).Methods(http.MethodPatch)
	officer.HandleFunc("/admin_document_type.AdminDocumentTypeHandler/Delete", handlerCtx.AdminDocumentTypeHandler.Delete).Methods(http.MethodDelete)
	officer.HandleFunc("/admin_officer.AdminOfficerHandler/Create", handlerCtx.AdminOfficerHandler.Create).Methods(http.MethodPost)
	officer.HandleFunc("/admin_officer.AdminOfficerHandler/Update", handlerCtx.AdminOfficerHandler.Update).Methods(http.MethodPatch)
	officer.HandleFunc("/admin_officer.AdminOfficerHandler/Delete", handlerCtx.AdminOfficerHandler.Delete).Methods(http.MethodDelete)
	officer.HandleFunc("/admin_officer_action.AdminOfficerActionHandler/Create", handlerCtx.AdminOfficerActionHandler.Create).Methods(http.MethodPost)
	officer.HandleFunc("/admin_officer_action.AdminOfficerActionHandler/Update", handlerCtx.AdminOfficerActionHandler.Update).Methods(http.MethodPatch)
	officer.HandleFunc("/admin_officer_action.AdminOfficerActionHandler/Delete", handlerCtx.AdminOfficerActionHandler.Delete).Methods(http.MethodDelete)

	recap := admin.PathPrefix("/recap").Subrouter()
	recap.Use(appConstants.PermissionRekapNilaiMiddleware, mw.PermissionMiddleware)
	recap.HandleFunc("/admin_student.AdminStudentHandler/GetSubjectGrade", handlerCtx.AdminStudentHandler.GetSubjectGrade).Methods(http.MethodGet)

	referenceData := admin.PathPrefix("/reference_data").Subrouter()
	referenceData.Use(appConstants.PermissionDataReferensiMiddleware, mw.PermissionMiddleware)
	referenceData.HandleFunc("/admin_subject_category.AdminSubjectCategoryHandler/Create", handlerCtx.AdminSubjectCategoryHandler.Create).Methods(http.MethodPost)
	referenceData.HandleFunc("/admin_subject_category.AdminSubjectCategoryHandler/Update", handlerCtx.AdminSubjectCategoryHandler.Update).Methods(http.MethodPatch)
	referenceData.HandleFunc("/admin_subject_category.AdminSubjectCategoryHandler/Delete", handlerCtx.AdminSubjectCategoryHandler.Delete).Methods(http.MethodDelete)
	referenceData.HandleFunc("/admin_shared_file.AdminSharedFileHandler/Approve", handlerCtx.AdminSharedFileHandler.Approve).Methods(http.MethodPatch)
	referenceData.HandleFunc("/admin_shared_file.AdminSharedFileHandler/Delete", handlerCtx.AdminSharedFileHandler.Delete).Methods(http.MethodDelete)
	referenceData.HandleFunc("/admin_announcement.AdminAnnouncementHandler/Create", handlerCtx.AdminAnnouncementHandler.Create).Methods(http.MethodPost)
	referenceData.HandleFunc("/admin_announcement.AdminAnnouncementHandler/Update", handlerCtx.AdminAnnouncementHandler.Update).Methods(http.MethodPatch)
	referenceData.HandleFunc("/admin_announcement.AdminAnnouncementHandler/Delete", handlerCtx.AdminAnnouncementHandler.Delete).Methods(http.MethodDelete)
	referenceData.HandleFunc("/admin_expertise_group.AdminExpertiseGroupHandler/Create", handlerCtx.AdminExpertiseGroupHandler.Create).Methods(http.MethodPost)
	referenceData.HandleFunc("/admin_expertise_group.AdminExpertiseGroupHandler/Update", handlerCtx.AdminExpertiseGroupHandler.Update).Methods(http.MethodPatch)
	referenceData.HandleFunc("/admin_expertise_group.AdminExpertiseGroupHandler/Delete", handlerCtx.AdminExpertiseGroupHandler.Delete).Methods(http.MethodDelete)

	registrationStatus := admin.PathPrefix("/registration_status").Subrouter()
	registrationStatus.Use(appConstants.PermissionStatusRegistrasiMiddleware, mw.PermissionMiddleware)
	registrationStatus.HandleFunc("/admin_student.AdminStudentHandler/BulkUpdatePayment", handlerCtx.AdminStudentHandler.BulkUpdatePayment).Methods(http.MethodPatch)
	registrationStatus.HandleFunc("/admin_student.AdminStudentHandler/GetPaymentLog", handlerCtx.AdminStudentHandler.GetPaymentLog).Methods(http.MethodGet)

	report := admin.PathPrefix("/report").Subrouter()
	report.Use(appConstants.PermissionLaporanMiddleware, mw.PermissionMiddleware)
	report.HandleFunc("/admin_report.AdminReportHandler/StudentStatus", handlerCtx.AdminReportHandler.StudentStatus).Methods(http.MethodGet)
	report.HandleFunc("/admin_report.AdminReportHandler/StudentClassGrade", handlerCtx.AdminReportHandler.StudentClassGrade).Methods(http.MethodGet)
	report.HandleFunc("/admin_report.AdminReportHandler/StudentProvince", handlerCtx.AdminReportHandler.StudentProvince).Methods(http.MethodGet)
	report.HandleFunc("/admin_report.AdminReportHandler/StudentSchoolProvince", handlerCtx.AdminReportHandler.StudentSchoolProvince).Methods(http.MethodGet)
	report.HandleFunc("/admin_report.AdminReportHandler/GpaDistribution", handlerCtx.AdminReportHandler.GpaDistribution).Methods(http.MethodGet)
	report.HandleFunc("/admin_report.AdminReportHandler/StudyDurationDistribution", handlerCtx.AdminReportHandler.StudyDurationDistribution).Methods(http.MethodGet)
	report.HandleFunc("/admin_report.AdminReportHandler/ThesisDurationDistribution", handlerCtx.AdminReportHandler.ThesisDurationDistribution).Methods(http.MethodGet)
	report.HandleFunc("/admin_report.AdminReportHandler/StudentStatusSummary", handlerCtx.AdminReportHandler.StudentStatusSummary).Methods(http.MethodGet)
	report.HandleFunc("/admin_report.AdminReportHandler/SubjectSummary", handlerCtx.AdminReportHandler.SubjectSummary).Methods(http.MethodGet)

	schedule := admin.PathPrefix("/schedule").Subrouter()
	schedule.Use(appConstants.PermissionJadwalMiddleware, mw.PermissionMiddleware)
	schedule.HandleFunc("/admin_class.AdminClassHandler/GetDetail", handlerCtx.AdminClassHandler.GetDetail).Methods(http.MethodGet)
	schedule.HandleFunc("/admin_class.AdminClassHandler/Create", handlerCtx.AdminClassHandler.Create).Methods(http.MethodPost)
	schedule.HandleFunc("/admin_class.AdminClassHandler/Update", handlerCtx.AdminClassHandler.Update).Methods(http.MethodPatch)
	schedule.HandleFunc("/admin_class.AdminClassHandler/UpdateActivation", handlerCtx.AdminClassHandler.UpdateActivation).Methods(http.MethodPatch)
	schedule.HandleFunc("/admin_class.AdminClassHandler/Delete", handlerCtx.AdminClassHandler.Delete).Methods(http.MethodDelete)
	schedule.HandleFunc("/admin_class.AdminClassHandler/Duplicate", handlerCtx.AdminClassHandler.Duplicate).Methods(http.MethodPost)

	semester := admin.PathPrefix("/semester").Subrouter()
	semester.Use(appConstants.PermissionSemesterMiddleware, mw.PermissionMiddleware)
	semester.HandleFunc("/admin_semester.AdminSemesterHandler/GetDetail", handlerCtx.AdminSemesterHandler.GetDetail).Methods(http.MethodGet)
	semester.HandleFunc("/admin_semester.AdminSemesterHandler/GetActive", handlerCtx.AdminSemesterHandler.GetActive).Methods(http.MethodGet)
	semester.HandleFunc("/admin_semester.AdminSemesterHandler/Create", handlerCtx.AdminSemesterHandler.Create).Methods(http.MethodPost)
	semester.HandleFunc("/admin_semester.AdminSemesterHandler/Update", handlerCtx.AdminSemesterHandler.Update).Methods(http.MethodPatch)
	semester.HandleFunc("/admin_semester.AdminSemesterHandler/UpdateActivation", handlerCtx.AdminSemesterHandler.UpdateActivation).Methods(http.MethodPatch)
	semester.HandleFunc("/admin_semester.AdminSemesterHandler/Delete", handlerCtx.AdminSemesterHandler.Delete).Methods(http.MethodDelete)

	skpi := admin.PathPrefix("/skpi").Subrouter()
	skpi.Use(appConstants.PermissionSKPIMiddleware, mw.PermissionMiddleware)
	skpi.HandleFunc("/admin_learning_achievement.AdminLearningAchievementHandler/Create", handlerCtx.AdminLearningAchievementHandler.Create).Methods(http.MethodPost)
	skpi.HandleFunc("/admin_learning_achievement.AdminLearningAchievementHandler/Update", handlerCtx.AdminLearningAchievementHandler.Update).Methods(http.MethodPatch)
	skpi.HandleFunc("/admin_learning_achievement.AdminLearningAchievementHandler/Delete", handlerCtx.AdminLearningAchievementHandler.Delete).Methods(http.MethodDelete)
	skpi.HandleFunc("/admin_learning_achievement_category.AdminLearningAchievementCategoryHandler/Create", handlerCtx.AdminLearningAchievementCategoryHandler.Create).Methods(http.MethodPost)
	skpi.HandleFunc("/admin_learning_achievement_category.AdminLearningAchievementCategoryHandler/Update", handlerCtx.AdminLearningAchievementCategoryHandler.Update).Methods(http.MethodPatch)
	skpi.HandleFunc("/admin_learning_achievement_category.AdminLearningAchievementCategoryHandler/Delete", handlerCtx.AdminLearningAchievementCategoryHandler.Delete).Methods(http.MethodDelete)
	skpi.HandleFunc("/admin_study_level.AdminStudyLevelHandler/UpdateSkpi", handlerCtx.AdminStudyLevelHandler.UpdateSkpi).Methods(http.MethodPatch)
	skpi.HandleFunc("/admin_student_skpi.AdminStudentSkpiHandler/GetDetail", handlerCtx.AdminStudentSkpiHandler.GetDetail).Methods(http.MethodGet)
	skpi.HandleFunc("/admin_student_skpi.AdminStudentSkpiHandler/Upsert", handlerCtx.AdminStudentSkpiHandler.Upsert).Methods(http.MethodPost)
	skpi.HandleFunc("/admin_student_skpi.AdminStudentSkpiHandler/Approve", handlerCtx.AdminStudentSkpiHandler.Approve).Methods(http.MethodPatch)
	skpi.HandleFunc("/admin_student_skpi.AdminStudentSkpiHandler/Delete", handlerCtx.AdminStudentSkpiHandler.Delete).Methods(http.MethodDelete)

	space := admin.PathPrefix("/space").Subrouter()
	space.Use(appConstants.PermissionManajemenRuangMiddleware, mw.PermissionMiddleware)
	space.HandleFunc("/admin_building.AdminBuildingHandler/GetDetail", handlerCtx.AdminBuildingHandler.GetDetail).Methods(http.MethodGet)
	space.HandleFunc("/admin_building.AdminBuildingHandler/Create", handlerCtx.AdminBuildingHandler.Create).Methods(http.MethodPost)
	space.HandleFunc("/admin_building.AdminBuildingHandler/Update", handlerCtx.AdminBuildingHandler.Update).Methods(http.MethodPatch)
	space.HandleFunc("/admin_building.AdminBuildingHandler/Delete", handlerCtx.AdminBuildingHandler.Delete).Methods(http.MethodDelete)
	space.HandleFunc("/admin_room.AdminRoomHandler/GetDetail", handlerCtx.AdminRoomHandler.GetDetail).Methods(http.MethodGet)
	space.HandleFunc("/admin_room.AdminRoomHandler/Create", handlerCtx.AdminRoomHandler.Create).Methods(http.MethodPost)
	space.HandleFunc("/admin_room.AdminRoomHandler/Update", handlerCtx.AdminRoomHandler.Update).Methods(http.MethodPatch)
	space.HandleFunc("/admin_room.AdminRoomHandler/Delete", handlerCtx.AdminRoomHandler.Delete).Methods(http.MethodDelete)
	space.HandleFunc("/admin_room.AdminRoomHandler/GetSchedule", handlerCtx.AdminRoomHandler.GetSchedule).Methods(http.MethodGet)

	adminStudent := admin.PathPrefix("/student").Subrouter()
	adminStudent.Use(appConstants.PermissionKemahasiswaanMiddleware, mw.PermissionMiddleware)
	adminStudent.HandleFunc("/admin_student.AdminStudentHandler/GetDetail", handlerCtx.AdminStudentHandler.GetDetail).Methods(http.MethodGet)
	adminStudent.HandleFunc("/admin_student.AdminStudentHandler/Create", handlerCtx.AdminStudentHandler.Create).Methods(http.MethodPost)
	adminStudent.HandleFunc("/admin_student.AdminStudentHandler/Update", handlerCtx.AdminStudentHandler.Update).Methods(http.MethodPatch)
	adminStudent.HandleFunc("/admin_student.AdminStudentHandler/Delete", handlerCtx.AdminStudentHandler.Delete).Methods(http.MethodDelete)
	adminStudent.HandleFunc("/admin_academic_guidance.AdminAcademicGuidanceHandler/Upsert", handlerCtx.AdminAcademicGuidanceHandler.Upsert).Methods(http.MethodPost)
	adminStudent.HandleFunc("/admin_student_leave.AdminStudentLeaveHandler/GetListRequests", handlerCtx.AdminStudentLeaveHandler.GetListRequests).Methods(http.MethodGet)
	adminStudent.HandleFunc("/admin_student_leave.AdminStudentLeaveHandler/GetList", handlerCtx.AdminStudentLeaveHandler.GetList).Methods(http.MethodGet)
	adminStudent.HandleFunc("/admin_student_leave.AdminStudentLeaveHandler/Create", handlerCtx.AdminStudentLeaveHandler.Create).Methods(http.MethodPost)
	adminStudent.HandleFunc("/admin_student_leave.AdminStudentLeaveHandler/Update", handlerCtx.AdminStudentLeaveHandler.Update).Methods(http.MethodPatch)
	adminStudent.HandleFunc("/admin_student_leave.AdminStudentLeaveHandler/Approve", handlerCtx.AdminStudentLeaveHandler.Approve).Methods(http.MethodPatch)
	adminStudent.HandleFunc("/admin_student_leave.AdminStudentLeaveHandler/End", handlerCtx.AdminStudentLeaveHandler.End).Methods(http.MethodPatch)
	adminStudent.HandleFunc("/admin_student.AdminStudentHandler/BulkUpdateStatus", handlerCtx.AdminStudentHandler.BulkUpdateStatus).Methods(http.MethodPatch)
	adminStudent.HandleFunc("/admin_student.AdminStudentHandler/GetStatusSummary", handlerCtx.AdminStudentHandler.GetStatusSummary).Methods(http.MethodGet)
	adminStudent.HandleFunc("/admin_student.AdminStudentHandler/ConvertGrade", handlerCtx.AdminStudentHandler.ConvertGrade).Methods(http.MethodPatch)

	studentActivity := admin.PathPrefix("/student_activity").Subrouter()
	studentActivity.Use(appConstants.PermissionAktivitasMahasiswaMiddleware, mw.PermissionMiddleware)
	studentActivity.HandleFunc("/admin_student_activity.AdminStudentActivityHandler/GetDetail", handlerCtx.AdminStudentActivityHandler.GetDetail).Methods(http.MethodGet)
	studentActivity.HandleFunc("/admin_student_activity.AdminStudentActivityHandler/Create", handlerCtx.AdminStudentActivityHandler.Create).Methods(http.MethodPost)
	studentActivity.HandleFunc("/admin_student_activity.AdminStudentActivityHandler/Update", handlerCtx.AdminStudentActivityHandler.Update).Methods(http.MethodPatch)
	studentActivity.HandleFunc("/admin_student_activity.AdminStudentActivityHandler/Delete", handlerCtx.AdminStudentActivityHandler.Delete).Methods(http.MethodDelete)

	studentClass := admin.PathPrefix("/student_class").Subrouter()
	studentClass.Use(appConstants.PermissionPesertaKelasMiddleware, mw.PermissionMiddleware)
	studentClass.HandleFunc("/admin_class.AdminClassHandler/GetClassParticipantList", handlerCtx.AdminClassHandler.GetClassParticipantList).Methods(http.MethodGet)
	studentClass.HandleFunc("/admin_class.AdminClassHandler/BulkUpdateMaximumParticipant", handlerCtx.AdminClassHandler.BulkUpdateMaximumParticipant).Methods(http.MethodPatch)
	studentClass.HandleFunc("/admin_student_class.AdminStudentClassHandler/TransferStudentClass", handlerCtx.AdminStudentClassHandler.TransferStudentClass).Methods(http.MethodPatch)
	studentClass.HandleFunc("/admin_student_class.AdminStudentClassHandler/ReshuffleStudentClass", handlerCtx.AdminStudentClassHandler.ReshuffleStudentClass).Methods(http.MethodPatch)
	studentClass.HandleFunc("/admin_student_class.AdminStudentClassHandler/MergeStudentClass", handlerCtx.AdminStudentClassHandler.MergeStudentClass).Methods(http.MethodPatch)
	studentClass.HandleFunc("/admin_lecture.AdminLectureHandler/BulkCreate", handlerCtx.AdminLectureHandler.BulkCreate).Methods(http.MethodPost)
	studentClass.HandleFunc("/admin_lecture.AdminLectureHandler/Update", handlerCtx.AdminLectureHandler.Update).Methods(http.MethodPatch)
	studentClass.HandleFunc("/admin_lecture.AdminLectureHandler/Delete", handlerCtx.AdminLectureHandler.Delete).Methods(http.MethodDelete)
	studentClass.HandleFunc("/admin_lecture.AdminLectureHandler/ResetParticipation", handlerCtx.AdminLectureHandler.ResetParticipation).Methods(http.MethodPatch)
	studentClass.HandleFunc("/admin_lecture.AdminLectureHandler/GetStudentParticipation", handlerCtx.AdminLectureHandler.GetStudentParticipation).Methods(http.MethodGet)
	studentClass.HandleFunc("/admin_lecturer.AdminLecturerHandler/GetAssignedClass", handlerCtx.AdminLecturerHandler.GetAssignedClass).Methods(http.MethodGet)
	studentClass.HandleFunc("/admin_exam_supervisor_role.AdminExamSupervisorRoleHandler/Create", handlerCtx.AdminExamSupervisorRoleHandler.Create).Methods(http.MethodPost)
	studentClass.HandleFunc("/admin_exam_supervisor_role.AdminExamSupervisorRoleHandler/Update", handlerCtx.AdminExamSupervisorRoleHandler.Update).Methods(http.MethodPatch)
	studentClass.HandleFunc("/admin_exam_supervisor_role.AdminExamSupervisorRoleHandler/Delete", handlerCtx.AdminExamSupervisorRoleHandler.Delete).Methods(http.MethodDelete)
	studentClass.HandleFunc("/admin_exam_supervisor.AdminExamSupervisorHandler/GetDetail", handlerCtx.AdminExamSupervisorHandler.GetDetail).Methods(http.MethodGet)
	studentClass.HandleFunc("/admin_exam_supervisor.AdminExamSupervisorHandler/Create", handlerCtx.AdminExamSupervisorHandler.Create).Methods(http.MethodPost)
	studentClass.HandleFunc("/admin_exam_supervisor.AdminExamSupervisorHandler/Update", handlerCtx.AdminExamSupervisorHandler.Update).Methods(http.MethodPatch)
	studentClass.HandleFunc("/admin_exam_supervisor.AdminExamSupervisorHandler/Delete", handlerCtx.AdminExamSupervisorHandler.Delete).Methods(http.MethodDelete)

	studyPlan := admin.PathPrefix("/study_plan").Subrouter()
	studyPlan.Use(appConstants.PermissionRencanaStudiMiddleware, mw.PermissionMiddleware)
	studyPlan.HandleFunc("/admin_study_plan.AdminStudyPlanHandler/BulkCreate", handlerCtx.AdminStudyPlanHandler.BulkCreate).Methods(http.MethodPost)

	studyPlanApproval := admin.PathPrefix("/study_plan_approval").Subrouter()
	studyPlanApproval.Use(appConstants.PermissionPersetujuanKRSMiddleware, mw.PermissionMiddleware)
	studyPlanApproval.HandleFunc("/admin_study_plan.AdminStudyPlanHandler/BulkApprove", handlerCtx.AdminStudyPlanHandler.BulkApprove).Methods(http.MethodPatch)

	studyProgram := admin.PathPrefix("/study_program").Subrouter()
	studyProgram.Use(appConstants.PermissionProgramStudiMiddleware, mw.PermissionMiddleware)
	studyProgram.HandleFunc("/admin_study_program.AdminStudyProgramHandler/GetDetail", handlerCtx.AdminStudyProgramHandler.GetDetail).Methods(http.MethodGet)
	studyProgram.HandleFunc("/admin_study_program.AdminStudyProgramHandler/Update", handlerCtx.AdminStudyProgramHandler.Update).Methods(http.MethodPatch)
	studyProgram.HandleFunc("/admin_accreditation.AdminAccreditationHandler/Create", handlerCtx.AdminAccreditationHandler.Create).Methods(http.MethodPost)
	studyProgram.HandleFunc("/admin_accreditation.AdminAccreditationHandler/Update", handlerCtx.AdminAccreditationHandler.Update).Methods(http.MethodPatch)
	studyProgram.HandleFunc("/admin_accreditation.AdminAccreditationHandler/Delete", handlerCtx.AdminAccreditationHandler.Delete).Methods(http.MethodDelete)

	thesis := admin.PathPrefix("/thesis").Subrouter()
	thesis.Use(appConstants.PermissionTugasAkhirMiddleware, mw.PermissionMiddleware)
	thesis.HandleFunc("/admin_thesis.AdminThesisHandler/GetDetail", handlerCtx.AdminThesisHandler.GetDetail).Methods(http.MethodGet)
	thesis.HandleFunc("/admin_thesis.AdminThesisHandler/Create", handlerCtx.AdminThesisHandler.Create).Methods(http.MethodPost)
	thesis.HandleFunc("/admin_thesis.AdminThesisHandler/Update", handlerCtx.AdminThesisHandler.Update).Methods(http.MethodPatch)
	thesis.HandleFunc("/admin_thesis.AdminThesisHandler/Delete", handlerCtx.AdminThesisHandler.Delete).Methods(http.MethodDelete)
	thesis.HandleFunc("/admin_thesis.AdminThesisHandler/RegisterThesisDefense", handlerCtx.AdminThesisHandler.RegisterThesisDefense).Methods(http.MethodPost)
	thesis.HandleFunc("/admin_thesis.AdminThesisHandler/CreateThesisDefense", handlerCtx.AdminThesisHandler.CreateThesisDefense).Methods(http.MethodPost)
	thesis.HandleFunc("/admin_thesis.AdminThesisHandler/UpdateThesisDefense", handlerCtx.AdminThesisHandler.UpdateThesisDefense).Methods(http.MethodPatch)
	thesis.HandleFunc("/admin_thesis_examiner_role.AdminThesisExaminerRoleHandler/Create", handlerCtx.AdminThesisExaminerRoleHandler.Create).Methods(http.MethodPost)
	thesis.HandleFunc("/admin_thesis_examiner_role.AdminThesisExaminerRoleHandler/Update", handlerCtx.AdminThesisExaminerRoleHandler.Update).Methods(http.MethodPatch)
	thesis.HandleFunc("/admin_thesis_examiner_role.AdminThesisExaminerRoleHandler/Delete", handlerCtx.AdminThesisExaminerRoleHandler.Delete).Methods(http.MethodDelete)
	thesis.HandleFunc("/admin_thesis_supervisor_role.AdminThesisSupervisorRoleHandler/Create", handlerCtx.AdminThesisSupervisorRoleHandler.Create).Methods(http.MethodPost)
	thesis.HandleFunc("/admin_thesis_supervisor_role.AdminThesisSupervisorRoleHandler/Update", handlerCtx.AdminThesisSupervisorRoleHandler.Update).Methods(http.MethodPatch)
	thesis.HandleFunc("/admin_thesis_supervisor_role.AdminThesisSupervisorRoleHandler/Delete", handlerCtx.AdminThesisSupervisorRoleHandler.Delete).Methods(http.MethodDelete)
	thesis.HandleFunc("/admin_thesis.AdminThesisHandler/GetThesisSupervisorLog", handlerCtx.AdminThesisHandler.GetThesisSupervisorLog).Methods(http.MethodGet)

	transcript := admin.PathPrefix("/transcript").Subrouter()
	transcript.Use(appConstants.PermissionTranskripMiddleware, mw.PermissionMiddleware)
	transcript.HandleFunc("/admin_transcript.AdminTranscriptHandler/GetDetail", handlerCtx.AdminTranscriptHandler.GetDetail).Methods(http.MethodGet)

	virtualClass := admin.PathPrefix("/virtual_class").Subrouter()
	virtualClass.Use(appConstants.PermissionVirtualClassMiddleware, mw.PermissionMiddleware)
	virtualClass.HandleFunc("/admin_class_work.AdminClassWorkHandler/GetSubmission", handlerCtx.AdminClassWorkHandler.GetSubmission).Methods(http.MethodGet)
	virtualClass.HandleFunc("/admin_class_discussion.AdminClassDiscussionHandler/GetComment", handlerCtx.AdminClassDiscussionHandler.GetComment).Methods(http.MethodGet)
	virtualClass.HandleFunc("/admin_class_exam.AdminClassExamHandler/GetSubmission", handlerCtx.AdminClassExamHandler.GetSubmission).Methods(http.MethodGet)

	// Career Handler

	career := s.PathPrefix("/career").Subrouter()
	career.Use(mw.CareerAccessToken)
	career.HandleFunc("/career_study_program.CareerStudyProgramHandler/GetList", handlerCtx.CareerStudyProgramHandler.GetList).Methods(http.MethodGet)
	career.HandleFunc("/career_study_program.CareerStudyProgramHandler/GetDetail", handlerCtx.CareerStudyProgramHandler.GetDetail).Methods(http.MethodGet)

	// General Handler

	general := s.PathPrefix("/general").Subrouter()
	general.Use(mw.GeneralAccessToken)
	general.HandleFunc("/general_file.GeneralFileHandler/UploadBase64Temp", handlerCtx.GeneralFileHandler.UploadBase64Temp).Methods(http.MethodPost)

	general.HandleFunc("/general_auth.GeneralAuthHandler/RefreshToken", handlerCtx.GeneralAuthHandler.RefreshToken).Methods(http.MethodPost)
	general.HandleFunc("/general_auth.GeneralAuthHandler/UpdatePassword", handlerCtx.GeneralAuthHandler.UpdatePassword).Methods(http.MethodPatch)
	general.HandleFunc("/general_auth.GeneralAuthHandler/Logout", handlerCtx.GeneralAuthHandler.Logout).Methods(http.MethodPost)
	general.HandleFunc("/general_location.GeneralLocationHandler/GetListCountry", handlerCtx.GeneralLocationHandler.GetListCountry).Methods(http.MethodGet)
	general.HandleFunc("/general_location.GeneralLocationHandler/GetListProvince", handlerCtx.GeneralLocationHandler.GetListProvince).Methods(http.MethodGet)
	general.HandleFunc("/general_location.GeneralLocationHandler/GetListRegency", handlerCtx.GeneralLocationHandler.GetListRegency).Methods(http.MethodGet)
	general.HandleFunc("/general_location.GeneralLocationHandler/GetListDistrict", handlerCtx.GeneralLocationHandler.GetListDistrict).Methods(http.MethodGet)
	general.HandleFunc("/general_location.GeneralLocationHandler/GetListVillage", handlerCtx.GeneralLocationHandler.GetListVillage).Methods(http.MethodGet)

	// Lecturer Handler

	lecturer := s.PathPrefix("/lecturer").Subrouter()
	lecturer.Use(mw.LecturerAccessToken)
	lecturer.HandleFunc("/lecturer_academic_guidance.LecturerAcademicGuidanceHandler/GetListStudent", handlerCtx.LecturerAcademicGuidanceHandler.GetListStudent).Methods(http.MethodGet)
	lecturer.HandleFunc("/lecturer_academic_guidance.LecturerAcademicGuidanceHandler/GetSessionList", handlerCtx.LecturerAcademicGuidanceHandler.GetSessionList).Methods(http.MethodGet)
	lecturer.HandleFunc("/lecturer_academic_guidance.LecturerAcademicGuidanceHandler/CreateSession", handlerCtx.LecturerAcademicGuidanceHandler.CreateSession).Methods(http.MethodPost)
	lecturer.HandleFunc("/lecturer_academic_guidance.LecturerAcademicGuidanceHandler/UpdateSession", handlerCtx.LecturerAcademicGuidanceHandler.UpdateSession).Methods(http.MethodPatch)
	lecturer.HandleFunc("/lecturer_academic_guidance.LecturerAcademicGuidanceHandler/DeleteSession", handlerCtx.LecturerAcademicGuidanceHandler.DeleteSession).Methods(http.MethodDelete)

	lecturer.HandleFunc("/lecturer_announcement.LecturerAnnouncementHandler/GetList", handlerCtx.LecturerAnnouncementHandler.GetList).Methods(http.MethodGet)

	lecturer.HandleFunc("/lecturer_class.LecturerClassHandler/GetActiveSemesterClassList", handlerCtx.LecturerClassHandler.GetActiveSemesterClassList).Methods(http.MethodGet)
	lecturer.HandleFunc("/lecturer_class.LecturerClassHandler/GetAssignedClass", handlerCtx.LecturerClassHandler.GetAssignedClass).Methods(http.MethodGet)
	lecturer.HandleFunc("/lecturer_class.LecturerClassHandler/GetAssignedSchedule", handlerCtx.LecturerClassHandler.GetAssignedSchedule).Methods(http.MethodGet)
	lecturer.HandleFunc("/lecturer_class.LecturerClassHandler/GetDetail", handlerCtx.LecturerClassHandler.GetDetail).Methods(http.MethodGet)
	lecturer.HandleFunc("/lecturer_class.LecturerClassHandler/BulkGradeStudentClass", handlerCtx.LecturerClassHandler.BulkGradeStudentClass).Methods(http.MethodPost)

	lecturer.HandleFunc("/lecturer_class_announcement.LecturerClassAnnouncementHandler/GetList", handlerCtx.LecturerClassAnnouncementHandler.GetList).Methods(http.MethodGet)
	lecturer.HandleFunc("/lecturer_class_announcement.LecturerClassAnnouncementHandler/Create", handlerCtx.LecturerClassAnnouncementHandler.Create).Methods(http.MethodPost)
	lecturer.HandleFunc("/lecturer_class_announcement.LecturerClassAnnouncementHandler/Update", handlerCtx.LecturerClassAnnouncementHandler.Update).Methods(http.MethodPatch)
	lecturer.HandleFunc("/lecturer_class_announcement.LecturerClassAnnouncementHandler/Delete", handlerCtx.LecturerClassAnnouncementHandler.Delete).Methods(http.MethodDelete)

	lecturer.HandleFunc("/lecturer_class_discussion.LecturerClassDiscussionHandler/GetList", handlerCtx.LecturerClassDiscussionHandler.GetList).Methods(http.MethodGet)
	lecturer.HandleFunc("/lecturer_class_discussion.LecturerClassDiscussionHandler/GetComment", handlerCtx.LecturerClassDiscussionHandler.GetComment).Methods(http.MethodGet)
	lecturer.HandleFunc("/lecturer_class_discussion.LecturerClassDiscussionHandler/Create", handlerCtx.LecturerClassDiscussionHandler.Create).Methods(http.MethodPost)
	lecturer.HandleFunc("/lecturer_class_discussion.LecturerClassDiscussionHandler/Update", handlerCtx.LecturerClassDiscussionHandler.Update).Methods(http.MethodPatch)
	lecturer.HandleFunc("/lecturer_class_discussion.LecturerClassDiscussionHandler/Delete", handlerCtx.LecturerClassDiscussionHandler.Delete).Methods(http.MethodDelete)
	lecturer.HandleFunc("/lecturer_class_discussion.LecturerClassDiscussionHandler/CreateComment", handlerCtx.LecturerClassDiscussionHandler.CreateComment).Methods(http.MethodPost)
	lecturer.HandleFunc("/lecturer_class_discussion.LecturerClassDiscussionHandler/DeleteComment", handlerCtx.LecturerClassDiscussionHandler.DeleteComment).Methods(http.MethodDelete)

	lecturer.HandleFunc("/lecturer_class_event.LecturerClassEventHandler/GetList", handlerCtx.LecturerClassEventHandler.GetList).Methods(http.MethodGet)
	lecturer.HandleFunc("/lecturer_class_event.LecturerClassEventHandler/Create", handlerCtx.LecturerClassEventHandler.Create).Methods(http.MethodPost)
	lecturer.HandleFunc("/lecturer_class_event.LecturerClassEventHandler/Update", handlerCtx.LecturerClassEventHandler.Update).Methods(http.MethodPatch)
	lecturer.HandleFunc("/lecturer_class_event.LecturerClassEventHandler/BulkUpdateActivation", handlerCtx.LecturerClassEventHandler.BulkUpdateActivation).Methods(http.MethodPatch)
	lecturer.HandleFunc("/lecturer_class_event.LecturerClassEventHandler/BulkDelete", handlerCtx.LecturerClassEventHandler.BulkDelete).Methods(http.MethodDelete)

	lecturer.HandleFunc("/lecturer_class_exam.LecturerClassExamHandler/GetList", handlerCtx.LecturerClassExamHandler.GetList).Methods(http.MethodGet)
	lecturer.HandleFunc("/lecturer_class_exam.LecturerClassExamHandler/GetSubmission", handlerCtx.LecturerClassExamHandler.GetSubmission).Methods(http.MethodGet)
	lecturer.HandleFunc("/lecturer_class_exam.LecturerClassExamHandler/Create", handlerCtx.LecturerClassExamHandler.Create).Methods(http.MethodPost)
	lecturer.HandleFunc("/lecturer_class_exam.LecturerClassExamHandler/Update", handlerCtx.LecturerClassExamHandler.Update).Methods(http.MethodPatch)
	lecturer.HandleFunc("/lecturer_class_exam.LecturerClassExamHandler/Delete", handlerCtx.LecturerClassExamHandler.Delete).Methods(http.MethodDelete)
	lecturer.HandleFunc("/lecturer_class_exam.LecturerClassExamHandler/GradeSubmission", handlerCtx.LecturerClassExamHandler.GradeSubmission).Methods(http.MethodPatch)

	lecturer.HandleFunc("/lecturer_class_grade_component.LecturerClassGradeComponentHandler/GetList", handlerCtx.LecturerClassGradeComponentHandler.GetList).Methods(http.MethodGet)
	lecturer.HandleFunc("/lecturer_class_grade_component.LecturerClassGradeComponentHandler/Set", handlerCtx.LecturerClassGradeComponentHandler.Set).Methods(http.MethodPatch)

	lecturer.HandleFunc("/lecturer_class_material.LecturerClassMaterialHandler/GetList", handlerCtx.LecturerClassMaterialHandler.GetList).Methods(http.MethodGet)
	lecturer.HandleFunc("/lecturer_class_material.LecturerClassMaterialHandler/Create", handlerCtx.LecturerClassMaterialHandler.Create).Methods(http.MethodPost)
	lecturer.HandleFunc("/lecturer_class_material.LecturerClassMaterialHandler/Update", handlerCtx.LecturerClassMaterialHandler.Update).Methods(http.MethodPatch)
	lecturer.HandleFunc("/lecturer_class_material.LecturerClassMaterialHandler/BulkUpdateActivation", handlerCtx.LecturerClassMaterialHandler.BulkUpdateActivation).Methods(http.MethodPatch)
	lecturer.HandleFunc("/lecturer_class_material.LecturerClassMaterialHandler/BulkDelete", handlerCtx.LecturerClassMaterialHandler.BulkDelete).Methods(http.MethodDelete)

	lecturer.HandleFunc("/lecturer_class_work.LecturerClassWorkHandler/GetList", handlerCtx.LecturerClassWorkHandler.GetList).Methods(http.MethodGet)
	lecturer.HandleFunc("/lecturer_class_work.LecturerClassWorkHandler/GetSubmission", handlerCtx.LecturerClassWorkHandler.GetSubmission).Methods(http.MethodGet)
	lecturer.HandleFunc("/lecturer_class_work.LecturerClassWorkHandler/Create", handlerCtx.LecturerClassWorkHandler.Create).Methods(http.MethodPost)
	lecturer.HandleFunc("/lecturer_class_work.LecturerClassWorkHandler/Update", handlerCtx.LecturerClassWorkHandler.Update).Methods(http.MethodPatch)
	lecturer.HandleFunc("/lecturer_class_work.LecturerClassWorkHandler/Delete", handlerCtx.LecturerClassWorkHandler.Delete).Methods(http.MethodDelete)
	lecturer.HandleFunc("/lecturer_class_work.LecturerClassWorkHandler/GradeSubmission", handlerCtx.LecturerClassWorkHandler.GradeSubmission).Methods(http.MethodPatch)

	lecturer.HandleFunc("/lecturer_general.LecturerGeneralHandler/GetSemesterSummary", handlerCtx.LecturerGeneralHandler.GetSemesterSummary).Methods(http.MethodGet)
	lecturer.HandleFunc("/lecturer_general.LecturerGeneralHandler/GetProfile", handlerCtx.LecturerGeneralHandler.GetProfile).Methods(http.MethodGet)

	lecturer.HandleFunc("/lecturer_lecture.LecturerLectureHandler/GetList", handlerCtx.LecturerLectureHandler.GetList).Methods(http.MethodGet)
	lecturer.HandleFunc("/lecturer_lecture.LecturerLectureHandler/GetDetail", handlerCtx.LecturerLectureHandler.GetDetail).Methods(http.MethodGet)
	// lecturer.HandleFunc("/lecturer_lecture.LecturerLectureHandler/Update", handlerCtx.LecturerLectureHandler.Update).Methods(http.MethodPatch)

	lecturer.HandleFunc("/lecturer_semester.LecturerSemesterHandler/GetList", handlerCtx.LecturerSemesterHandler.GetList).Methods(http.MethodGet)

	lecturer.HandleFunc("/lecturer_shared_file.LecturerSharedFileHandler/GetList", handlerCtx.LecturerSharedFileHandler.GetList).Methods(http.MethodGet)
	lecturer.HandleFunc("/lecturer_shared_file.LecturerSharedFileHandler/Create", handlerCtx.LecturerSharedFileHandler.Create).Methods(http.MethodPost)
	lecturer.HandleFunc("/lecturer_shared_file.LecturerSharedFileHandler/Update", handlerCtx.LecturerSharedFileHandler.Update).Methods(http.MethodPatch)
	lecturer.HandleFunc("/lecturer_shared_file.LecturerSharedFileHandler/Delete", handlerCtx.LecturerSharedFileHandler.Delete).Methods(http.MethodDelete)

	lecturer.HandleFunc("/lecturer_study_program.LecturerStudyProgramHandler/GetList", handlerCtx.LecturerStudyProgramHandler.GetList).Methods(http.MethodGet)

	pmb := s.PathPrefix("/pmb").Subrouter()
	pmb.Use(mw.PmbAccessToken)
	pmb.HandleFunc("/pmb_student.PmbStudentHandler/BulkCreate", handlerCtx.PmbStudentHandler.BulkCreate).Methods(http.MethodPost)

	// Root Handler

	root := s.PathPrefix("/root").Subrouter()
	root.Use(mw.RootAccessToken)
	root.HandleFunc("/root_admin.RootAdminHandler/GetList", handlerCtx.RootAdminHandler.GetList).Methods(http.MethodGet)
	root.HandleFunc("/root_admin.RootAdminHandler/Create", handlerCtx.RootAdminHandler.Create).Methods(http.MethodPost)
	root.HandleFunc("/root_admin.RootAdminHandler/Update", handlerCtx.RootAdminHandler.Update).Methods(http.MethodPatch)
	root.HandleFunc("/root_admin.RootAdminHandler/Delete", handlerCtx.RootAdminHandler.Delete).Methods(http.MethodDelete)

	root.HandleFunc("/root_admin_activity_log.RootAdminActivityLogHandler/GetList", handlerCtx.RootAdminActivityLogHandler.GetList).Methods(http.MethodGet)
	root.HandleFunc("/root_lecturer_student_activity_log.RootLecturerStudentActivityLogHandler/GetList", handlerCtx.RootLecturerStudentActivityLogHandler.GetList).Methods(http.MethodGet)

	root.HandleFunc("/root_dikti_study_program.RootDiktiStudyProgramHandler/GetList", handlerCtx.RootDiktiStudyProgramHandler.GetList).Methods(http.MethodGet)

	root.HandleFunc("/root_faculty.RootFacultyHandler/GetList", handlerCtx.RootFacultyHandler.GetList).Methods(http.MethodGet)
	root.HandleFunc("/root_faculty.RootFacultyHandler/GetDetail", handlerCtx.RootFacultyHandler.GetDetail).Methods(http.MethodGet)
	root.HandleFunc("/root_faculty.RootFacultyHandler/Create", handlerCtx.RootFacultyHandler.Create).Methods(http.MethodPost)
	root.HandleFunc("/root_faculty.RootFacultyHandler/Update", handlerCtx.RootFacultyHandler.Update).Methods(http.MethodPatch)
	root.HandleFunc("/root_faculty.RootFacultyHandler/Delete", handlerCtx.RootFacultyHandler.Delete).Methods(http.MethodDelete)

	root.HandleFunc("/root_lecturer.RootLecturerHandler/GetList", handlerCtx.RootLecturerHandler.GetList).Methods(http.MethodGet)

	root.HandleFunc("/root_major.RootMajorHandler/GetList", handlerCtx.RootMajorHandler.GetList).Methods(http.MethodGet)
	root.HandleFunc("/root_major.RootMajorHandler/GetDetail", handlerCtx.RootMajorHandler.GetDetail).Methods(http.MethodGet)
	root.HandleFunc("/root_major.RootMajorHandler/Create", handlerCtx.RootMajorHandler.Create).Methods(http.MethodPost)
	root.HandleFunc("/root_major.RootMajorHandler/Update", handlerCtx.RootMajorHandler.Update).Methods(http.MethodPatch)
	root.HandleFunc("/root_major.RootMajorHandler/Delete", handlerCtx.RootMajorHandler.Delete).Methods(http.MethodDelete)

	root.HandleFunc("/root_permission.RootPermissionHandler/GetList", handlerCtx.RootPermissionHandler.GetList).Methods(http.MethodGet)

	root.HandleFunc("/root_role.RootRoleHandler/GetList", handlerCtx.RootRoleHandler.GetList).Methods(http.MethodGet)
	root.HandleFunc("/root_role.RootRoleHandler/Create", handlerCtx.RootRoleHandler.Create).Methods(http.MethodPost)
	root.HandleFunc("/root_role.RootRoleHandler/Update", handlerCtx.RootRoleHandler.Update).Methods(http.MethodPatch)
	root.HandleFunc("/root_role.RootRoleHandler/Delete", handlerCtx.RootRoleHandler.Delete).Methods(http.MethodDelete)

	root.HandleFunc("/root_study_program.RootStudyProgramHandler/GetList", handlerCtx.RootStudyProgramHandler.GetList).Methods(http.MethodGet)
	root.HandleFunc("/root_study_program.RootStudyProgramHandler/GetDetail", handlerCtx.RootStudyProgramHandler.GetDetail).Methods(http.MethodGet)
	root.HandleFunc("/root_study_program.RootStudyProgramHandler/Create", handlerCtx.RootStudyProgramHandler.Create).Methods(http.MethodPost)
	root.HandleFunc("/root_study_program.RootStudyProgramHandler/Update", handlerCtx.RootStudyProgramHandler.Update).Methods(http.MethodPatch)
	root.HandleFunc("/root_study_program.RootStudyProgramHandler/Delete", handlerCtx.RootStudyProgramHandler.Delete).Methods(http.MethodDelete)

	student := s.PathPrefix("/student").Subrouter()
	student.Use(mw.StudentAccessToken)

	student.HandleFunc("/student_academic_guidance.StudentAcademicGuidanceHandler/GetDetail", handlerCtx.StudentAcademicGuidanceHandler.GetDetail).Methods(http.MethodGet)
	student.HandleFunc("/student_academic_guidance.StudentAcademicGuidanceHandler/GetSessionList", handlerCtx.StudentAcademicGuidanceHandler.GetSessionList).Methods(http.MethodGet)

	student.HandleFunc("/student_announcement.StudentAnnouncementHandler/GetList", handlerCtx.StudentAnnouncementHandler.GetList).Methods(http.MethodGet)

	student.HandleFunc("/student_class.StudentClassHandler/GetOfferedClassList", handlerCtx.StudentClassHandler.GetOfferedClassList).Methods(http.MethodGet)
	student.HandleFunc("/student_class.StudentClassHandler/GetOfferedSchedule", handlerCtx.StudentClassHandler.GetOfferedSchedule).Methods(http.MethodGet)
	student.HandleFunc("/student_class.StudentClassHandler/GetTakenClass", handlerCtx.StudentClassHandler.GetTakenClass).Methods(http.MethodGet)

	student.HandleFunc("/student_class_announcement.StudentClassAnnouncementHandler/GetList", handlerCtx.StudentClassAnnouncementHandler.GetList).Methods(http.MethodGet)

	student.HandleFunc("/student_class_discussion.StudentClassDiscussionHandler/GetList", handlerCtx.StudentClassDiscussionHandler.GetList).Methods(http.MethodGet)
	student.HandleFunc("/student_class_discussion.StudentClassDiscussionHandler/GetComment", handlerCtx.StudentClassDiscussionHandler.GetComment).Methods(http.MethodGet)
	student.HandleFunc("/student_class_discussion.StudentClassDiscussionHandler/CreateComment", handlerCtx.StudentClassDiscussionHandler.CreateComment).Methods(http.MethodPost)
	student.HandleFunc("/student_class_discussion.StudentClassDiscussionHandler/DeleteComment", handlerCtx.StudentClassDiscussionHandler.DeleteComment).Methods(http.MethodDelete)

	student.HandleFunc("/student_class_event.StudentClassEventHandler/GetList", handlerCtx.StudentClassEventHandler.GetList).Methods(http.MethodGet)

	student.HandleFunc("/student_class_exam.StudentClassExamHandler/GetList", handlerCtx.StudentClassExamHandler.GetList).Methods(http.MethodGet)
	student.HandleFunc("/student_class_exam.StudentClassExamHandler/Submit", handlerCtx.StudentClassExamHandler.Submit).Methods(http.MethodPost)

	student.HandleFunc("/student_class_material.StudentClassMaterialHandler/GetList", handlerCtx.StudentClassMaterialHandler.GetList).Methods(http.MethodGet)

	student.HandleFunc("/student_class_work.StudentClassWorkHandler/GetList", handlerCtx.StudentClassWorkHandler.GetList).Methods(http.MethodGet)
	student.HandleFunc("/student_class_work.StudentClassWorkHandler/Submit", handlerCtx.StudentClassWorkHandler.Submit).Methods(http.MethodPost)

	student.HandleFunc("/student_general.StudentGeneralHandler/GetSemesterSummary", handlerCtx.StudentGeneralHandler.GetSemesterSummary).Methods(http.MethodGet)
	student.HandleFunc("/student_general.StudentGeneralHandler/GetProfile", handlerCtx.StudentGeneralHandler.GetProfile).Methods(http.MethodGet)
	student.HandleFunc("/student_general.StudentGeneralHandler/UpdateProfile", handlerCtx.StudentGeneralHandler.UpdateProfile).Methods(http.MethodPatch)
	student.HandleFunc("/student_general.StudentGeneralHandler/GetParentProfile", handlerCtx.StudentGeneralHandler.GetParentProfile).Methods(http.MethodGet)
	student.HandleFunc("/student_general.StudentGeneralHandler/UpdateParentProfile", handlerCtx.StudentGeneralHandler.UpdateParentProfile).Methods(http.MethodPatch)
	student.HandleFunc("/student_general.StudentGeneralHandler/GetSchoolProfile", handlerCtx.StudentGeneralHandler.GetSchoolProfile).Methods(http.MethodGet)
	student.HandleFunc("/student_general.StudentGeneralHandler/UpdateSchoolProfile", handlerCtx.StudentGeneralHandler.UpdateSchoolProfile).Methods(http.MethodPatch)

	student.HandleFunc("/student_grade_type.StudentGradeTypeHandler/GetList", handlerCtx.StudentGradeTypeHandler.GetList).Methods(http.MethodGet)

	student.HandleFunc("/student_lecture.StudentLectureHandler/GetHistory", handlerCtx.StudentLectureHandler.GetHistory).Methods(http.MethodGet)
	student.HandleFunc("/student_lecture.StudentLectureHandler/AttendAutonomousLecture", handlerCtx.StudentLectureHandler.AttendAutonomousLecture).Methods(http.MethodPatch)

	student.HandleFunc("/student_semester.StudentSemesterHandler/GetList", handlerCtx.StudentSemesterHandler.GetList).Methods(http.MethodGet)

	student.HandleFunc("/student_shared_file.StudentSharedFileHandler/GetList", handlerCtx.StudentSharedFileHandler.GetList).Methods(http.MethodGet)

	student.HandleFunc("/student_student_leave.StudentStudentLeaveHandler/GetListRequests", handlerCtx.StudentStudentLeaveHandler.GetListRequests).Methods(http.MethodGet)
	student.HandleFunc("/student_student_leave.StudentStudentLeaveHandler/Create", handlerCtx.StudentStudentLeaveHandler.Create).Methods(http.MethodPost)
	student.HandleFunc("/student_student_leave.StudentStudentLeaveHandler/Update", handlerCtx.StudentStudentLeaveHandler.Update).Methods(http.MethodPatch)

	student.HandleFunc("/student_student_skpi.StudentStudentSkpiHandler/GetDetail", handlerCtx.StudentStudentSkpiHandler.GetDetail).Methods(http.MethodGet)
	student.HandleFunc("/student_student_skpi.StudentStudentSkpiHandler/Upsert", handlerCtx.StudentStudentSkpiHandler.Upsert).Methods(http.MethodPost)

	student.HandleFunc("/student_study_plan.StudentStudyPlanHandler/GetDetail", handlerCtx.StudentStudyPlanHandler.GetDetail).Methods(http.MethodGet)
	student.HandleFunc("/student_study_plan.StudentStudyPlanHandler/Create", handlerCtx.StudentStudyPlanHandler.Create).Methods(http.MethodPost)

	student.HandleFunc("/student_thesis.StudentThesisHandler/GetDetail", handlerCtx.StudentThesisHandler.GetDetail).Methods(http.MethodGet)
	student.HandleFunc("/student_thesis.StudentThesisHandler/Create", handlerCtx.StudentThesisHandler.Create).Methods(http.MethodPost)
	student.HandleFunc("/student_thesis.StudentThesisHandler/Update", handlerCtx.StudentThesisHandler.Update).Methods(http.MethodPatch)

	student.HandleFunc("/student_transcript.StudentTranscriptHandler/GetDetail", handlerCtx.StudentTranscriptHandler.GetDetail).Methods(http.MethodGet)

	excel := admin.PathPrefix("/excel").Subrouter()
	excel.Use(mw.AdminAccessToken)

	excel.HandleFunc("/admin_excel.ExcelHandler/StudyProgramDistributionDownload", handlerCtx.ExcelHandler.StudyProgramDistributionDownload).Methods(http.MethodGet)

	return r
}
