// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: admin/class_grade_component.proto

package class_grade_component

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdminClassGradeComponentHandlerClient is the client API for AdminClassGradeComponentHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminClassGradeComponentHandlerClient interface {
	GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponse, error)
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
}

type adminClassGradeComponentHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminClassGradeComponentHandlerClient(cc grpc.ClientConnInterface) AdminClassGradeComponentHandlerClient {
	return &adminClassGradeComponentHandlerClient{cc}
}

func (c *adminClassGradeComponentHandlerClient) GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponse, error) {
	out := new(GetListResponse)
	err := c.cc.Invoke(ctx, "/admin_class_grade_component.AdminClassGradeComponentHandler/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClassGradeComponentHandlerClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, "/admin_class_grade_component.AdminClassGradeComponentHandler/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminClassGradeComponentHandlerServer is the server API for AdminClassGradeComponentHandler service.
// All implementations must embed UnimplementedAdminClassGradeComponentHandlerServer
// for forward compatibility
type AdminClassGradeComponentHandlerServer interface {
	GetList(context.Context, *GetListRequest) (*GetListResponse, error)
	Set(context.Context, *SetRequest) (*SetResponse, error)
	mustEmbedUnimplementedAdminClassGradeComponentHandlerServer()
}

// UnimplementedAdminClassGradeComponentHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedAdminClassGradeComponentHandlerServer struct {
}

func (UnimplementedAdminClassGradeComponentHandlerServer) GetList(context.Context, *GetListRequest) (*GetListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedAdminClassGradeComponentHandlerServer) Set(context.Context, *SetRequest) (*SetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedAdminClassGradeComponentHandlerServer) mustEmbedUnimplementedAdminClassGradeComponentHandlerServer() {
}

// UnsafeAdminClassGradeComponentHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminClassGradeComponentHandlerServer will
// result in compilation errors.
type UnsafeAdminClassGradeComponentHandlerServer interface {
	mustEmbedUnimplementedAdminClassGradeComponentHandlerServer()
}

func RegisterAdminClassGradeComponentHandlerServer(s grpc.ServiceRegistrar, srv AdminClassGradeComponentHandlerServer) {
	s.RegisterService(&AdminClassGradeComponentHandler_ServiceDesc, srv)
}

func _AdminClassGradeComponentHandler_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminClassGradeComponentHandlerServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_class_grade_component.AdminClassGradeComponentHandler/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminClassGradeComponentHandlerServer).GetList(ctx, req.(*GetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminClassGradeComponentHandler_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminClassGradeComponentHandlerServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_class_grade_component.AdminClassGradeComponentHandler/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminClassGradeComponentHandlerServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminClassGradeComponentHandler_ServiceDesc is the grpc.ServiceDesc for AdminClassGradeComponentHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminClassGradeComponentHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin_class_grade_component.AdminClassGradeComponentHandler",
	HandlerType: (*AdminClassGradeComponentHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _AdminClassGradeComponentHandler_GetList_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _AdminClassGradeComponentHandler_Set_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/class_grade_component.proto",
}
